### ISSUE TITLE
mega-menu is not keyboard accessible

### ISSUE THREAD

**Issue by StdGit** [wet-boew/cdts-sgdc#102]
Hey Martin,

No I’m no longer with the CDTS project but I’ve cc’d the generic mailbox for those who are.

This issue has something to do with the intranet template coming from TBS. 

Feel free to open an issue on the CDTS project.

https://github.com/wet-boew/cdts-sgdc/issues

Shawn Thompson 
Conseiller technique en accessibilité Web | Web Accessibility Technical Advisor
Accessibilité TI / DGIIT | IT Accessibility / IITB
Email | Courriel Shawn.Thompson@hrsdc-rhdcc.gc.ca
Telephone | Téléphone 438-892-1834
Government of Canada | Gouvernement du Canada

From: Robitaille, Martin M [NC] <martin.robitaille@servicecanada.gc.ca> 
Sent: February 17, 2020 1:16 PM
To: Thompson, Shawn S [NC] <shawn.thompson@hrsdc-rhdcc.gc.ca>
Cc: NC-CS-SC-PFOLIO-WEB-WEB-MINIST-INTRANET-GD <NC-CS-SC-PFOLIO-WEB-WEB-MINIST-INTRANET-GD@hrdc-drhc.net>; Perry, Benoit B [NC] <benoit.perry@servicecanada.gc.ca>; Millette, Radji RJC [NC] <radji.millette@hrsdc-rhdcc.gc.ca>
Subject: CDTS - Intranet

Hey Shawn,

Quick question, are you still managing the Intranet CDTS? We noticed that our mega-menu is not keyboard accessible…

Is this something you would be responsible for or is it now another team that maintains this??

Let me know, thanks!

Martin Robitaille

Spécialiste principal de projets Web / Senior Web Project Specialist 
Web ministériel / Portfolio Web 
Direction générale de service aux citoyens / Citizen Service Branch
Service Canada 
Gouvernement du Canada / Government of Canada
martin.robitaille@servicecanada.gc.ca 
819-654-7241

**Comment by mrobitaille07** [comment]
Hello, if you load any pages on our Intranet site, if we use the keyboard Tab key, we can't access any links on the mega-menu. 

Let me know if you can look into it... thank you!
http://esdc.prv/en/index.shtml

**Comment by ipaksc** [comment]
Hi Martin: To fix the issue. You have to find another way to hide GCTools information.

An element is focusable if none of its ancestors are display: none, therefore GCTools anchors <a> are not focusable.

The issue is not related to CDTS template.
