### ISSUE TITLE
Canada.ca "Home" breadcrumb

### ISSUE THREAD

**Issue by ghost-girl** [wet-boew/cdts-sgdc#119]
I was just wondering if you are currently in the works of renaming the Canada.ca "Home" breadcrumb to instead say "Canada.ca"? Our clients have notified us that this is the new standard, but haven't seen this updated in the CDTS template yet.

Thanks!

**Comment by StdGit** [comment]
@ipaksc Could you close the issue if everything is ok ?

**Comment by ipaksc** [comment]
The task has been completed.
