### ISSUE TITLE
Canada.ca breadcrumb should remain even when adding additional breadcrumbs

### ISSUE THREAD

**Issue by s-laugh** [wet-boew/cdts-sgdc#120]
Issue open under the DotNetTemplates: https://gccode.ssc-spc.gc.ca/iitb-dgiit/sds/GOCWebTemplates/DotNetTemplates/issues/366

**Summary**: The root breadcrumb should remain when adding additional breadcrumbs.

**_Expanded (text from issue link above)_**
Is there any intention of having the Canada.ca "Home" breadcrumb stay at the beginning of the breadcrumb list even when adding additional breadcrumbs? The Canada.ca "Home" breadcrumb is automatically added to a page if the breadcrumbs aren't touched, but as soon as I want to add my own it overwrites the existing Home breadcrumb. Currently I have to add the Canada.ca "Home" breadcrumb to all of the apps that I support here at TC and I'd imagine there are other groups having to do the same thing so it'd be nice if the template could always automatically do this, or even just have an option within the template to turn this on or off.

**Comment by StdGit** [comment]
@ipaksc Could you close the issue, if everything is ok, Thx

**Comment by ipaksc** [comment]
The task has been completed

**Comment by StdGit** [comment]
Note: 
See the use case in (Cdts mailbox)
Behavior for GC Web and Application templates differs.
Ex: For GC Web template, Canada.ca is always added, even if  a link already exist
https://ssl-templates.services.gc.ca/app/cls/WET/gcweb/v4_0_32c/cdts/samples/breadcrumbs-en.shtml
