### ISSUE TITLE
Check if CDTS could run on linux and other os , safari, android etc.

### ISSUE THREAD

**Issue by StdGit** [wet-boew/cdts-sgdc#122]
Check if CDTS could run on linux and other os , safari, android etc.

Since canada.ca is rewriting in lower case, it could be lead to some error

Click on https://www.canada.ca/etc/designs/canada/cdts/gcweb/v4_0_32c/cdts/appTop/refFooter_exitscript-en.shtml

and then on http://csszengarden.com/219 at the bottom of the page

ref**F**ooter_exitscript-en.shtml is renamed reffooter_exitscript-en.shtml

P.S The site will be updated and we couldn't reproduce the error.

**Comment by duboisp** [comment]
the error is here where the function `toLowerCase()` is called: https://github.com/wet-boew/cdts-sgdc/blob/master/_src/js/exitScript.js#L12

I tracked down the issue, here the trace
* The test page “RefTop” – Line 121 in the source code of https://www.canada.ca/etc/designs/canada/cdts/gcweb/v4_0_32c/cdts/appTop/refFooter_exitscript-en.shtml 
  * The docs is not copied over the new github repo and it is not included in this either.
* When the code to initiate the exit script is generated -  https://github.com/wet-boew/cdts-sgdc/blob/master/_src/soy/gcweb/en/gcweb-en.soy#L435
* The exit script script - https://github.com/wet-boew/cdts-sgdc/blob/master/_src/js/exitScript.js#L12

**Comment by StdGit** [comment]
Fixed but have to be deploy on https://www.canada.ca/etc/designs/canada/cdts/gcweb/v4_0_32c

You could test here

https://ssl-templates.services.gc.ca/app/cls/WET/gcweb/v4_0_32c/cdts/apptop_test/reffooter_exitscript-en.shtml

**Comment by ahmad-shahid** [comment]
Already been fixed. Closing this issue.
