### ISSUE TITLE
GTM Google tag analytics

### ISSUE THREAD

**Issue by StdGit** [wet-boew/cdts-sgdc#123]
I would like to know why we are using GTM

**Comment by StdGit** [comment]
@nicolasraymond

Hi Nicolas, do you know the answer?.

**Comment by nicolasraymond** [comment]
We tried using GTM to know who is using the CDTS. GTM should be striped from the code.

**Comment by ahmad-shahid** [comment]
GTM script has been removed in the latest release (v4.0.39). Closing issue.
