### ISSUE TITLE
Exit Script renders "true = 0;" text below the footer footer

### ISSUE THREAD

**Issue by jonnorth** [wet-boew/cdts-sgdc#124]
While testing exit script fix that was applied in the new version 4.0.32c fix #115   the fix works and links with target=”_blank” now open in a new window/tab but it looks like there is another issue where some text (true = 0;) is inserted at the bottom of the page.

For Example see the sample below at the very left bottom of the page you’ll see the text “true = 0;” 
[https://www.canada.ca/etc/designs/canada/cdts/gcweb/v4_0_32c/cdts/samples/exitscript-en.shtml](https://www.canada.ca/etc/designs/canada/cdts/gcweb/v4_0_32c/cdts/samples/exitscript-en.shtml)

**Comment by StdGit** [comment]
Fixed in CDTS
https://ssl-templates.services.gc.ca/app/cls/WET/gcweb/v4_0_32c/cdts/samples_test/exitscript-en.shtml
