### ISSUE TITLE
Using date picker logs user out if "exitScript" is true on IE

### ISSUE THREAD

**Issue by nicholas-ly** [wet-boew/cdts-sgdc#125]
For v4.0.32, when using the [date picker](https://wet-boew.github.io/wet-boew/demos/datepicker/datepicker-en.html) coupled with the `wet.builder.refFooter` `exitScript` set to `true`, the `exitURL` is hit when selecting attempting to select a date in Internet Explorer 11.

The issue also occurs for v4.0.31 but not previous versions.

This issue does not occur for Chrome, Edge or Firefox.

**Comment by StdGit** [comment]
Thx,

We have fixed it
You could test here
https://ssl-templates.services.gc.ca/app/cls/WET/gcweb/v4_0_32c/cdts/samples_test/zzz_exitscript-datepicker-en.shtml
It will be include in the next release

**Comment by patricehernert** [comment]
@nicholas-ly Could you confirm this issue has been fixed in version 4.0.39 ? Thanks.

**Comment by nicholas-ly** [comment]
@patricehernert In 4.0.39, the date picker no longer shows up in Internet Explorer 11. The date picker is showing up correctly in Chrome, Edge and Firefox.

**Comment by ahmad-shahid** [comment]
IE is no longer supported. Closing this issue.
