### ISSUE TITLE
Accessibility Issue and Analytics ?

### ISSUE THREAD

**Issue by StdGit** [wet-boew/cdts-sgdc#127]
We have integrated the CDTS into our Emergency Platform Universe Access Scripts had a few accessibility defects raised against our application
 
![image](https://user-images.githubusercontent.com/5129874/83918473-cbfb1300-a746-11ea-81c6-b293dae5735c.png)

Some of the items appear to be caused by the CDTS:

**Comment by nicolasraymond** [comment]
J'ai regardé et en fait le CDTS a corrigé les problèmes. J'ai répondu au client.
