### ISSUE TITLE
Add nav elements for

### ISSUE THREAD

**Issue by StdGit** [wet-boew/cdts-sgdc#129]
The Canada.ca templates were changed and now wrapping the top skip to main content navigation in a nav. Should we update it in CDTS? 

Does it help accessibility
Is there side effects (Check ajax inclusion)

Documentation:
(https://www.w3.org/WAI/GL/wiki/Grouping_related_links_using_the_nav_element)

Canada.ca

```
<nav>
<ul>
                <li href="#wb-cont">Skip to main content</a></li>
[…]
</ul>
</nav> 
```

CDTS

```
<div id="def-top">
			<!-- Write closure fall-back static file -->
			<!-- /ROOT/app/cls/WET/gcweb/v4_0_32c/cdts/static/appTop-en.html -->
					<ul id="wb-tphp">
			<li class="wb-slc"><a class="wb-sl" href="#wb-cont">Skip to main content</a></li>
			<li class="wb-slc visible-sm visible-md visible-lg"><a class="wb-sl" href="#wb-info">Skip to "About this Web application"</a></li>
			<!-- If you have a custom footer, replace the previous line with this one
			<li class="wb-slc visible-sm visible-md visible-lg"><a class="wb-sl" href="#wb-info">Skip to "Related links"</a></li>
			-->
			<!-- If you have a section menu 
			<li class="wb-slc visible-md visible-lg"><a class="wb-sl" href="#wb-sec">Skip to section menu</a></li>
			-->
		</ul>

```

**Comment by nicolasraymond** [comment]
Accessibility is fine

**Comment by szet0018** [comment]
Is there an update on this issue?

Should an aria-label be added to the nav since there are multiple nav? I chose an aria-label because there is no heading for the Skip links, otherwise I would have chosen aria-labelledby="headingForSkipLinks".

E.g.
`<nav aria-label="Skip links">
<ul>
                <li href="#wb-cont">Skip to main content</a></li>
[…]
</ul>
</nav> `
