### ISSUE TITLE
Add descriptive Title in cdts samples

### ISSUE THREAD

**Issue by StdGit** [wet-boew/cdts-sgdc#131]
Change generic `<title>Content page - Canada.ca</title>` for a specialized title

Ex: Title for
[https://ssl-templates.services.gc.ca/app/cls/WET/gcweb/v4_0_32/cdts/samples/breadcrumbs-en.shtml](url)

will be

`<title>breadcrumbs-en</title>`

You can also change the date 
`defPreFooter.outerHTML = wet.builder.preFooter({
					"dateModified": "2020-09-11"
				});`

**Comment by ahmad-shahid** [comment]
Sample pages were revamped which addressed this issue.
