### ISSUE TITLE
Character encoding

### ISSUE THREAD

**Issue by StdGit** [wet-boew/cdts-sgdc#133]
On https://ssl-templates.services.gc.ca/app/cls/WET/gcweb/v4_0_32c/cdts/appTop/refFooter_exitscript-en.shtml

We receive those errors

> 10:50:58.377 The character encoding of the plain text document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the file needs to be declared in the transfer protocol or file needs to use a byte order mark as an encoding signature. en.min.js

> 10:50:58.722 The character encoding of the plain text document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the file needs to be declared in the transfer protocol or file needs to use a byte order mark as an encoding signature.

**Comment by ahmad-shahid** [comment]
@StdGit I don't see the error in the link you provided. Is this still an issue?

**Comment by ahmad-shahid** [comment]
Errors are no longer present. Closing issue.
