### ISSUE TITLE
FW: Une en-tête de Canada.ca plus mince pour les écrans mobiles | A slimmer Canada.ca header for mobile screens 

### ISSUE THREAD

**Issue by StdGit** [wet-boew/cdts-sgdc#135]
À vérifier avant d'implémenter la prochaine version du CDTS

Verify before implementing next version of CDTS

https://github.com/wet-boew/gcweb/releases/tag/v8.0.

**Comment by ahmad-shahid** [comment]
Implemented for v4.0.43.

![image](https://user-images.githubusercontent.com/52757738/124481993-d9823280-dd76-11eb-9f1f-8a05d7ae347e.png)
