### ISSUE TITLE
On Google Chrome, we get a warning "A parser-blocking, cross site (i.e. different eTLD+1) script

### ISSUE THREAD

**Issue by StdGit** [wet-boew/cdts-sgdc#136]
On Google Chrome, we get a warning "A parser-blocking, cross site (i.e. different eTLD+1) script, is invoked via document.write." for javascript reference on canada.ca

open originally in
https://gccode.ssc-spc.gc.ca/iitb-dgiit/sds/GOCWebTemplates/DotNetTemplates/-/issues/274

Should be fixed by implementing exitScript in wet-boew https://github.com/wet-boew/wet-boew/pull/8894

**Comment by ahmad-shahid** [comment]
The wet-boew issue that is referred here has been closed. For the document.write problem, that is being tracked here: #55
