### ISSUE TITLE
Google Tag Manager Script ?

### ISSUE THREAD

**Issue by Moro-Code** [wet-boew/cdts-sgdc#139]
Hello,

I noticed that CDTS injects a google tag manager script. Is there anyway to disable this or at least get a sense of what information is being collected?

**Comment by StdGit** [comment]
We will remove it in next version for technical reasons. 
It was use only for statistic.

**Comment by ahmad-shahid** [comment]
Hi @Moro-Code, the script was removed in the latest release v4.0.39. Can this issue be closed?
