### ISSUE TITLE
Create CONTRIBUTING file

### ISSUE THREAD

**Issue by shawnthompson** [wet-boew/cdts-sgdc#14]
Need to add a CONTRIBUTING file to talk about the roles of all contributors should be employees of GoC and the security requirements

https://help.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors

**Comment by pabrams** [comment]
I see there's already a file created in the root.  Can this issue be closed?  At first I thought there was some stuff missing (how to build, etc.), but I think it's all covered in the README.md.
