### ISSUE TITLE
Custom header navigation not generating proper ARIA menu tags

### ISSUE THREAD

**Issue by brandonandre** [wet-boew/cdts-sgdc#140]
Hello,

I am currently running on version "v4_0_32" of CDTS. 

Using CDTS to generate the AppTop, I decided to use a custom navigation menu which generates the following HTML:

```
<ul class="list-inline menu" role="menubar">
	<li>
		<a href="/taxonomy/TaxonMain.php" class="item">Home</a>
	</li>
	...
</ul>
```

But looking on this page: https://cenw-wscoe.github.io/sgdc-cdts/GCWeb/appTop/apptop_all-en.html

It generates the following:

```
<ul class="list-inline menu" role="menubar">
	<li class="">
		<a href="#" class="item" tabindex="0" aria-posinset="1" aria-setsize="3" role="menuitem">Overview</a>
	</li>
	...
</ul>
```

My generated HTML is missing the following attributes: `tabindex="0" aria-posinset="1" aria-setsize="3" role="menuitem"`

------------------

I believe the example is using "menuPath" reference instead of the "menuLinks". I'm not sure if that's the reason why this is happening or if I'm doing something wrong on my end.

Here is the code used to generate my AppTop:

```
<script type="text/javascript">
    var defTop = document.getElementById("def-top");
	defTop.outerHTML = wet.builder.appTop({
        // Application Name
        "appName": [{
            "text": "Canadian National Collection (CNC)",
            "href": "/taxonomy/TaxonMain.php"
        }],

        // Application language toggle.
        "lngLinks": [{
            "lang": "fr",
            "href": "?lang=fr",
            "text": "Français"
         }],

        // Menu Buttons
        "menuLinks": [
            // Home button
            {
                  "href": "/taxonomy/TaxonMain.php",
                   "text": "Home"
            },
            
            // Taxonomy Search
            {
                "href": "/taxonomy/TaxonSearch.php",
                "text": "Taxon Search"
            },
     
            // Specimen Search
            {
                "href": "/taxonomy/SpecSearchD15.php",
                "text": "Specimen Search"
            }, 
            
            // Opened Specimen
            {
                "href": "/taxonomy/Specimen.php",
                "text": "Opened Specimen"
            }, 
            
            // Interactive Determination
            {
                "href": "/taxonomy/IDIndex.php",
                "text": "I.D."
            },
            
            // Manual - Always display the manual.
            {
                "href": "/taxonomy/files/CNCManual20170815.pdf",
                "text": "Manual"
            }
                    ]
	});  
</script>
```

Thanks in advance!

**Comment by brandonandre** [comment]
#141 - Created a pull request

**Comment by ipaksc** [comment]
@ brandonandre Hi Andre

The listed attributes is not part of CDTS template.

Here is my test page. The generated HTML has all attributes.

https://ssl-templates.services.gc.ca/app/cls/WET/gcweb/v4_0_32c/cdts/apptop_ilya/apptop_breadcrumbs-en.shtml

![Capture](https://user-images.githubusercontent.com/7250664/87675975-07293280-c746-11ea-93d6-76e0f051488f.JPG)

**Comment by brandonandre** [comment]
Thanks for the quick response.

Interesting, perhaps I setup CDTS incorrectly in my project. I'm going to go through the guide on the website again and make sure I followed all the steps.

Thanks!
