### ISSUE TITLE
FIP no longer appearing with 4.0.27

### ISSUE THREAD

**Issue by richardjpotter** [wet-boew/cdts-sgdc#142]
Last week, we noticed a few of our applications in production are no longer displaying the FIP/Canada logo.
The browser console displays the following errors:

>  Refused to display 'https://www.canada.ca/etc/designs/canada/cdts/gcweb/v4_0_27/assets/wmms-blk.svg' in a frame because it set 'X-Frame-Options' to 'sameorigin'.
> Refused to display 'https://www.canada.ca/etc/designs/canada/cdts/gcweb/v4_0_27/assets/sig-blk-en.svg' in a frame because it set 'X-Frame-Options' to 'sameorigin'.
 
Switching to 4_0_30 corrects the issue, but causes UI layout issues, so it's not a viable option.
 
For reference, here is the code we use in our web.config:
 
    <GoC.WebTemplate version="v4_0_27" environment="Akamai" loadJQueryFromGoogle="true" showPreContent="true" showPostContent="true" showFeedbackLink="true" feedbackLinkUrl="" showLanguageLink="true" showSharePageLink="true" showSearch="true" showFeatures="true" staticFilesLocation="~\Views\GoC.WebTemplate\StaticFallbackFiles" xmlns="http://tempuri.org/WebTemplateMVC.xsd">
        <sessionTimeOut enabled="false" inactivity="1200000" reactionTime="180000" sessionalive="1200000" logouturl="#" refreshCallbackUrl="#" refreshOnClick="false" refreshLimit="120000" method="" additionalData="" />
        <leavingSecureSiteWarning enabled="false" displayModalWindow="true" redirectURL="" excludedDomains="" />
    </GoC.WebTemplate>

**Comment by StdGit** [comment]
Hi Richard

> Switching to 4_0_30 corrects the issue, but causes UI layout issues.

Could you send a print screen of your issue, and specify the browser you used

Note: I don't have the error you specified in version 4_0_27 in Firefox, Do you still have the issue?

**Comment by richardjpotter** [comment]
Hello,

This is the issue currently.  Note the FIP is missing, and the 3 errors in the console window.
This is in Chrome, but the issue exists in other browsers also.
[cid:image001.jpg@01D664D3.7D1B3360]

The issue presents differently in IE:

[cid:image002.jpg@01D664D3.7D1B3360]

**Comment by StdGit** [comment]
sites on *.ic.gc.ca. seems have the same error
The loading of “https://www.canada.ca/etc/designs/canada/cdts/gcweb/v4_0_25/assets/sig-blk-en.svg” in a frame is denied by “X-Frame-Options“ directive set to “SAMEORIGIN“.

And the error seems to be in wet-boew too
https://github.com/wet-boew/wet-boew/issues/5189

**Comment by cussond123** [comment]
Same issue with some apps at our department Indigenous Services Canada.
Refused to display 'https://www.canada.ca/etc/designs/canada/cdts/gcweb/v4_0_26/assets/sig-blk-en.svg' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

We sent an email to NC-SGDC-CDTS-GD@hrsdc-rhdcc.gc.ca but no response.

**Comment by ahmad-shahid** [comment]
Confirmed via email that this issue has been resolved.
