### ISSUE TITLE
Ajouter une section référence de liens dans la documentation

### ISSUE THREAD

**Issue by StdGit** [wet-boew/cdts-sgdc#144]
Ajouter dans
https://cenw-wscoe.github.io/sgdc-cdts/docs/index-en.html

Les liens suivants:

Workshop resources
Web Experience Toolkit / GCWeb: 
•	Web Experience Toolkit - https://wet-boew.github.io/
•	GCWeb / Canada.ca theme - https://wet-boew.github.io/themes-dist/GCWeb/index-en.html
•	Quick implementation guide - GCWeb theme - https://wet-boew.github.io/themes-dist/GCWeb/gcweb-theme/implementing.html
WET-BOEW code sprints: 
•	Location: Place du Centre, 200 promenade du portage, Gatineau, suite 990, room 2D302
•	When: Every week on Tuesday from 9h30 to 15h30
•	Goal: You can work on WET related projects and have on-site support.
•	Type: Unstructured, which means there is no official agenda. From time to time, and if needed, there can be a structured code sprint.
•	To join: Contact Pierre Dubois, you can find his contact information on gccollab or on gcconnect or on twitter via @duboi5p
Centrally Deployed Templates Solution: 
•	What is CDTS? - https://bit.ly/whatiscdts
•	CDTS - https://cenw-wscoe.github.io/sgdc-cdts/docs/index-en.html
•	Implementing GCWeb with CDTS - https://cenw-wscoe.github.io/sgdc-cdts/docs/internet-en.html
•	CDTS registration page (subscribe for updates) - https://www.gcpedia.gc.ca/wiki/Centrally_Deployed_Templates_Solution_(CDTS)/Registration
•	CDTS .NET templates - https://gccode.ssc-spc.gc.ca/iitb-dgiit/sds/GOCWebTemplates/DotNetTemplates 
•	CDTS Java templates - https://gccode.ssc-spc.gc.ca/iitb-dgiit/sds/GOCWebTemplates/JavaTemplates

**Comment by ahmad-shahid** [comment]
Moved issue to https://github.com/cenw-wscoe/sgdc-cdts/issues/16 - CDTS documentation repo.
