### ISSUE TITLE
Unique accessible labels for nav

### ISSUE THREAD

**Issue by szet0018** [wet-boew/cdts-sgdc#146]
This is regarding the CDTS application template.

I am getting an axe accessibility error because the nav for the menubar at Main navigation menu (id="wb-sm") and About this web application (class="col-md-10") do not have unique accessible names.

This can be resolved by adding an aria-labelledby reference on the nav to the visually hidden headings in the nav.

`<nav id='wb-sm' aria-labelledby='appMenu">`
`[...]`
`<h2 class="wb-inv" id="appMenu">Main navigation menu</h2>`
`[...]`
`<nav aria-labelledby="about">...`
`<h2 id="about" class="wb-inv">About this web application</h2>`

**Comment by ahmad-shahid** [comment]
This issue has been fixed.
