### ISSUE TITLE
<li> elements must be contained in a <ul> or <ol> - accessibility issue on axe

### ISSUE THREAD

**Issue by szet0018** [wet-boew/cdts-sgdc#147]
The aXe accessibility checker is reporting the following issue on the CDTS application template.

li elements must be contained in a ul or ol

**Issue description**
Ensures li elements are used semantically
Impact: serious

Element location:
.menu > li:nth-child(1)
.menu > li:nth-child(2)
.menu > li:nth-child(3)

Element source
`<li><a href="#" class="item" tabindex="0" aria-posinset="1" aria-setsize="3" role="menuitem">Overview</a></li>`

The issue here is that the ul is given role="menubar", which results in an axe error for the li because in this context, the ul is no longer a list, so the li is missing a parent ul.

A potential solution can be found at:
https://www.w3.org/TR/wai-aria-practices/examples/menubar/menubar-1/menubar-1.html

In this solution, the li are given role="none".

Example Code:
`<ul class="list-inline menu" role="menubar">`
`<li class="" role="none"><a href="#" class="item" tabindex="0" aria-posinset="1" aria-setsize="3" role="menuitem">Overview</a></li>`
`<li role="none"><a href="#" class="item" tabindex="-1" aria-posinset="2" aria-setsize="3" role="menuitem">First section</a></li>`
`...`

**Comment by ahmad-shahid** [comment]
Issue has been fixed; role="none" added as per the W3C guidelines (https://www.w3.org/TR/wai-aria-practices/examples/menubar/menubar-1/menubar-1.html).
