### ISSUE TITLE
Does CDN is 24/7 compliant

### ISSUE THREAD

**Issue by StdGit** [wet-boew/cdts-sgdc#148]
EX:

![image](https://user-images.githubusercontent.com/5129874/89909207-cf829e80-dbbc-11ea-8859-e5279838a811.png)

**Comment by ahmad-shahid** [comment]
@StdGit Can you please provide more details for this issue?

**Comment by ahmad-shahid** [comment]
@StdGit Can you please provide more details for this issue?
