### ISSUE TITLE
File is not load in the footer

### ISSUE THREAD

**Issue by StdGit** [wet-boew/cdts-sgdc#151]
Hi,
It’s about the footer include files of eadc.prv, when the footer include file is updated, it did not show the updates in esdc.prv
The includes file:
http://esdc.prv/includes/edsc-esdc_prv/wet4/fr/footer/esdcfooter-fra.html

web page:
http://esdc.prv/fr/dgsm/gace-structure-gouvernance-comites-portefeuille-edsc.shtml 

would you please check the include file path?

**Comment by StdGit** [comment]
This 2 errors could affect the behavior
 
![image](https://user-images.githubusercontent.com/5129874/91460342-b3862a80-e855-11ea-9ec3-6e56a0c4e124.png)

**Comment by ahmad-shahid** [comment]
Confirmed via email on Aug 28th that is issue has been resolved.
