### ISSUE TITLE
Dependabot alerts in Github

### ISSUE THREAD

**Issue by StdGit** [wet-boew/cdts-sgdc#153]
https://github.com/wet-boew/cdts-sgdc/network/alerts

This one should be prioritized:

https://github.com/wet-boew/cdts-sgdc/network/alert/package-lock.json/websocket-extensions/open

**Comment by ahmad-shahid** [comment]
Project has been restructured and this is addressed in the new code.

**Comment by nschonni** [comment]
This isn't addressed by the project restructure, but would be by https://github.com/wet-boew/cdts-sgdc/pull/250

**Comment by nschonni** [comment]
Sorry, that particular might have been addressed, but not the ongoing Dependabot setup
