### ISSUE TITLE
Skip to "About government" is missing in smaller screen sizes

### ISSUE THREAD

**Issue by sarasuri** [wet-boew/cdts-sgdc#155]
Hi,
 
Noticed, when viewing Web pages in various smaller screen sizes that are implemented using CDTS, the 'Skip to "About government"' link is missing at the top of the pages.

**Comment by patricehernert** [comment]
For now, I don't have the repo for GitHub, so I will try to fix the issue inside GCCode.

Moreover, I'm not able to assign myself an issue. For that, I have to be added to the team.

**Comment by patricehernert** [comment]
@sarasuri Hi! Could you give a link where I can see the problem ? Do you say the link '"Skip to "About government"' is displayed on bigger screen sizes, and disappears when we reduces the size of the screen ? Thanks.

**Comment by ahmad-shahid** [comment]
@sarasuri Is it possible if you could provide a link and/or a screenshot?

**Comment by sarasuri** [comment]
Here is the link to one of the CDTS demo pages with the above issue: https://cenw-wscoe.github.io/sgdc-cdts/GCWeb/samples/content-en.html
The page is viewed in Chrome. Below are screenshots with and without the "Skip to "About government' link.

**Comment by ahmad-shahid** [comment]
This has now been fixed.

**Comment by ahmad-shahid** [comment]
![image](https://user-images.githubusercontent.com/52757738/139850401-d1e9750b-54d0-4caa-99bb-b50087c3cc7f.png)
