### ISSUE TITLE
Remove unnecessary SSI Directives cdnEnv

### ISSUE THREAD

**Issue by StdGit** [wet-boew/cdts-sgdc#157]
Our samples have a lot of this line (SSI directive)

`<!--#if expr = "$vrSrvr != canada" -->"cdnEnv": "<!--#echo encoding="none" var="vrSrvr"-->"<!--#endif-->`

In Gcweb it is used only in {template .environment}, so we could remove these lines in the samples

Verify before removing it, if the environment template is not called` "{call .environment"` by the template that you are using.

**But we can't remove them in Gcintranet** since it is used in many templates like {template .appFooter}

**Comment by StdGit** [comment]
See also https://github.com/wet-boew/cdts-sgdc/issues/158

**Comment by StdGit** [comment]
Since we are removing SSI, we will need to hardcode the environment.
The default server was:
https://www.canada.ca/etc/designs/canada/cdts

**Comment by ahmad-shahid** [comment]
SSI statements have been removed as part of v4.0.39 release and the environment has been hardcoded.
