### ISSUE TITLE
The href tag in the French version is missing the “#’ in the menuLinks in appTop

### ISSUE THREAD

**Issue by jeanbenoitrochon** [wet-boew/cdts-sgdc#159]
The href tag in the French version is missing the “#’ in the menuLinks in appTop

Snippet from email received from client:

**_issue reported on past versions 4.0.31, 4.0.32 were breaking their menus and they reverted to 4.0.30_**

...

**_problem with generating custom menus at the top of the page using the menuLinks in appTop.  There is a problem when I switch to French.

In the CDTS code there appears to be a bug.  If you visit the links below you will see 

https://github.com/wet-boew/cdts-sgdc/blob/master/_src/soy/gcweb/fr/gcweb-appPage-fr.soy#L204 
 https://github.com/wet-boew/cdts-sgdc/blob/master/_src/soy/gcweb/en/gcweb-appPage-en.soy#L203 

The href tag in the French version is missing the “#’.  This is causing unpredictable behaviour.  Hopefully that change will fix all of the issues I am having.  I need this fixed because of an upcoming release._**

**Comment by ahmad-shahid** [comment]
Fixed with 4.0.39 release. Closing issue.
