### ISSUE TITLE
Bypass blocks causing accessibility issue certain browsers

### ISSUE THREAD

**Issue by Kamla55** [wet-boew/cdts-sgdc#161]
An issue encountered with CDTS the same is encountered on the canada.ca site as well.

Bypass blocks are invisible causing an accessibility issue for certain OS/Browser combinations.
•	Behaviour in Mac: Firefox - The tab focus does not go to the blocks.
•	Behaviour in iPad: Voiceover + Chrome -  The bypass blocks read but not highlighted in a contrastic color.

Example of the bypass block being referred (highlighted in red border) - 
![browser behaviour](https://user-images.githubusercontent.com/71461405/94047050-8b7bdf80-fd9f-11ea-9154-738b0d6d703e.gif)

**Comment by patricehernert** [comment]
@Kamla55 Could you confirm this issue still exists in version 4.0.39 ? Thanks.

**Comment by Kamla55** [comment]
Hold on checking with the client - they will test and let us know

**Comment by ahmad-shahid** [comment]
hey @Kamla55, would you know if the clients got back to you regarding this issue? Thanks.

**Comment by ahmad-shahid** [comment]
Closing. If this issue occurs, we can reopen.
