### ISSUE TITLE
Static files are not on Canada.ca

### ISSUE THREAD

**Issue by StdGit** [wet-boew/cdts-sgdc#162]
It looks Static files are missing on the run version on Canada.ca
The rn version should be based on v4.0.32

https://www.canada.ca/etc/designs/canada/cdts/gcweb/rn/cdts/static/refTop.html breaks

https://www.canada.ca/etc/designs/canada/cdts/gcweb/v4_0_32/cdts/static/refTop.html works

https://www.canada.ca/etc/designs/canada/cdts/gcweb/v4_0_32c/cdts/static/refTop.html works

**Comment by ahmad-shahid** [comment]
Static pages for the Canada.ca theme are found here: https://cenw-wscoe.github.io/sgdc-cdts/docs/index-en.html
