### ISSUE TITLE
In site-menu-v5-fr GTM is passed as parameter

### ISSUE THREAD

**Issue by StdGit** [wet-boew/cdts-sgdc#169]
Is there a reason why Google Tag Manager is passed as a parameter?

<li role="presentation"><a role="menuitem" tabindex="-1" href="https://www.ic.gc.ca/app/scr/cc/CorporationsCanada/hm.html?f=&amp;selectedDirectorUuid=%3BselectedIncorporatorUuid%3D&amp;metricsId=GTM-WQQH22">Apporter des changements à votre société (Centre de dépôt en ligne)</a></li>

**Comment by ahmad-shahid** [comment]
We get this file from the WET package. It would be best to ask this question in the WET repo.
