### ISSUE TITLE
Sample Pages: Identify which blocks of code we want to include in sample pages 

### ISSUE THREAD

**Issue by jeanbenoitrochon** [wet-boew/cdts-sgdc#178]
the content of the sample pages are not consistent.
Certain sample pages uses a certain block of html code and in other pages another block of code is used but they should all be the same.

identify which blocks of code should be used in all of the pages.

Once the "standard blocks" are defined then we can apply the blocks on all of the pages.

**Comment by ahmad-shahid** [comment]
The content of the sample pages has been updated.
