### ISSUE TITLE
Repo description contains broken GitHub pages link

### ISSUE THREAD

**Issue by EricDunsworth** [wet-boew/cdts-sgdc#18]
I noticed that the description in [this repo's main page](https://github.com/wet-boew/cdts-sgdc) is currently leading to a 404 error page:
> Centrally Deployed Templates Solution (CDTS) / Solution de gabarits à déploiement centralisé (SGDC) https://cenw-wscoe.github.io/sgdc-cdts/

I thought maybe it was just an outdated link, so I tried changing the subdomain from "cenw-wscoe" to "wet-boew" to get https://wet-boew.github.io/sgdc-cdts/... but it still didn't work.

This repo has a ``gh-pages`` branch, but it doesn't seem to be taking effect at the moment. Maybe something needs to be adjusted in the repo's settings to activate it?

If it doesn't turn out to be a configuration error in the repo's settings, maybe it could have something to do with the ``gh-pages`` branch somehow clashing with [wet-boew/wet-boew.github.io](https://github.com/wet-boew/wet-boew.github.io)? Although FWIW I wasn't able to find anything in [GitHub Help](https://help.github.com/en/github/working-with-github-pages/about-github-pages#types-of-github-pages-sites) about organization sites being known to override project sites. So maybe it's something else.

**Comment by shawnthompson** [comment]
Whoops, it's now fixed.

https://github.com/cenw-wscoe/sgdc-cdts

Thanks for looking out!
