### ISSUE TITLE
css?family=Noto are skipped during build

### ISSUE THREAD

**Issue by StdGit** [wet-boew/cdts-sgdc#191]
https://travis-ci.org/github/wet-boew/cdts-sgdc/builds/744513792

Running "cssmin:dist" (cssmin) task

>> Skipping remote @import of "https://fonts.googleapis.com/css?family=Noto+Sans:400,700,400italic,700italic&subset=latin,latin-ext" as no callback given.,Skipping remote @import of "https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic&subset=latin,latin-ext" as no callback given.

>> Skipping remote @import of "https://fonts.googleapis.com/css?family=Noto+Sans:400,700,400italic,700italic&subset=latin,latin-ext" as no callback given.,Skipping remote @import of "https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic&subset=latin,latin-ext" as no callback given.

**Comment by ahmad-shahid** [comment]
Project has been restructured. Closing issue.
