### ISSUE TITLE
"Cannot set property 'innerHTML' of null" error causing French pages to render incorrectly.

### ISSUE THREAD

**Issue by dannysheppard** [wet-boew/cdts-sgdc#193]
I'm seeing the following error in the console when viewing French pages. This only occurs so far on our test server, it has not been deployed to production so I don't know how it will behave there, and the issue does not occur when I test locally. The only issue to note about the test server is that it very slow to respond to requests.

I see this on all French pages when I deploy them to our test server. As a result, the page does not render correctly. The title, search box, custom menu, and inview section are not displayed. See attached screenshots.

![samplePageEnglish](https://user-images.githubusercontent.com/28925380/99821755-6ba73480-2b20-11eb-8177-c8bb1757c239.jpg)
![samplePageFrench](https://user-images.githubusercontent.com/28925380/99821838-7eba0480-2b20-11eb-996a-180aa2d55f9b.jpg)

The rendering behaviour has been inconsistent. Sometimes I see parts of the page like the menu, but not the search box or vice versa, for example. Most times, neither is displayed.

This is for ORT which is an intranet application using CDTS version 4.0.32.

`Uncaught TypeError: Cannot set property 'innerHTML' of null
    at h (wet-boew.js:7403)
    at u (wet-boew.js:7476)
    at q (wet-boew.js:7156)
    at HTMLElement.<anonymous> (wet-boew.js:7624)
    at HTMLDocument.dispatch (jquery.min.js:3)
    at HTMLDocument.r.handle (jquery.min.js:3)
    at Object.trigger (jquery.min.js:4)
    at HTMLElement.<anonymous> (jquery.min.js:4)
    at Function.each (jquery.min.js:2)
    at n.fn.init.each (jquery.min.js:2)`

I have debugged and it seems the issue is coming down to some missing attributes. On English pages, I see the following tag:

`<nav role="navigation" id="wb-sm" data-ajax-replace="./ajax/sitemenu-en.html" data-trgt="mb-pnl" class="wb-menu visible-md visible-lg" typeof="SiteNavigationElement">`

However in the French page, the same tag looks like:

`<nav role="navigation" id="wb-sm" class="wb-menu visible-md visible-lg" typeof="SiteNavigationElement">`

**Comment by StdGit** [comment]
In which browsers these issues happens ?

**Comment by dannysheppard** [comment]
It happens in Edge, IE 11, Firefox,  and Chrome.

**Comment by StdGit** [comment]
I have another bug with ajax. Servers have been modified recently and Cors have been modified 
@jeanbenoitrochon @duboisp 

X-Frame-Options http header is set to be the same origin on canada.ca.

https://github.com/wet-boew/cdts-sgdc/issues/156

To follow

**Comment by dannysheppard** [comment]
Update on this issue. It looks like I was able to get the French page working by changing the time that the call to wet.builder.appTop(). I still can't explain why English worked but French did not. The reason for the failure appears to be that the call to wet.builder.appTop() was wrapped in a onload() block which waited for JavaScript to load on the page. Still testing, but this appears to have resolved the issue we are seeing.

**Comment by ahmad-shahid** [comment]
Hi @dannysheppard, if this has been resolved, can I go ahead and close this issue? Thanks

**Comment by dannysheppard** [comment]
Yes I think this can be closed.
