### ISSUE TITLE
INTRANET - search box missing on blog.prv

### ISSUE THREAD

**Issue by Kamla55** [wet-boew/cdts-sgdc#194]
Ran the WAVE plugin on blogs.prv (not esdc.prv) homepage and it flagged the search field in the left nav was an empty field.

What It Means: 
A form label is present, but does not contain any content.
Why It Matters:
A <label> element that is associated to a form control but does not contain text will not present any information about the form control to the user.
How to Fix It:
Ensure that the form label contains text that describes the function of the associated form control. Labels are not required for image, submit, reset, button, or hidden form controls. If a label is not necessary visually, a descriptive title attribute may be added to the form control.

**Comment by jeanbenoitrochon** [comment]
Please provide URL so we can reproduce.

**Comment by Kamla55** [comment]
http://esdc.prv/en/lb/index.shtml

**Comment by ahmad-shahid** [comment]
Hello, I ran the wave plugin on the URL provided and I'm unable to reproduce that error. It says the label is there and is associated with the form control. I also checked via code. Is it possible if you could send a screenshot/report of the issue you see? Thanks!

![image](https://user-images.githubusercontent.com/52757738/100891040-dba1ad00-3486-11eb-81c9-c07969aaecb6.png)
![image](https://user-images.githubusercontent.com/52757738/100891262-16a3e080-3487-11eb-82fd-526fc93fc3c5.png)

**Comment by Radji-Millette** [comment]
The issue is on http://blogs-blogues.prv/?lang=en. Not esdc.prv.

1 X Empty form label

**Comment by ahmad-shahid** [comment]
I noticed the error is occurring in the label tag `<label display="none" for="s" />` 
This code is not being rendered by CDTS. If you populate this label with content, on your end, this issue should be fixed.

**Comment by ahmad-shahid** [comment]
Hope this has been fixed on your end. Closing this issue, thanks.
