### ISSUE TITLE
INTRANET HTML5 plugin for chat wizard

### ISSUE THREAD

**Issue by Kamla55** [wet-boew/cdts-sgdc#197]
Pls ensure next release on v4.0.39 includes HTML5 plugin for chat wizard

**Comment by ahmad-shahid** [comment]
Moving to backlog: 

Chat wizard is still an unstable (provisional) feature (https://wet-boew.github.io/themes-dist/GCWeb/demos/chatwizard/chatwizard-en.html). 

Also, from email "Chat wizard component is now months away from WET documentation, and we are going to do a work around, using the Wizard code as a plugin / not in WET"

**Comment by ahmad-shahid** [comment]
Closing this issue. We can revisit if when it is time to implement this feature.
