### ISSUE TITLE
popup is not displayed for external link

### ISSUE THREAD

**Issue by nguyenpearl** [wet-boew/cdts-sgdc#198]
When the user clicks on contact link in the footer, the popup waring that the user will be logged out is not displayed

**Comment by ahmad-shahid** [comment]
This is issue has now been fixed. Please re-test and let me know if I can close this issue.

**Comment by nguyenpearl** [comment]
I will test and let you know. thanks

**Comment by nguyenpearl** [comment]
Hi,

I tested in both .net and java applications in our group by clicking on the contact information link in def-footer section

[cid:image001.png@01D6D650.8062E1A0]

Here is the result of my tests:

1/ For java apps:


-          Version 4.0.30: click on external link, a popup displays. If user click no, return the user to the current page. If user click yes, log user out and redirect him to external link.

-          Version 4.0.32: clicking on external link, no popup displays. User is logged out and redirected to external link

-          Version 4.0.39: clicking on external link, no popup displays. User is logged out but not redirected to external link.
2. For .NET apps:
     - Version 4.0.32, there is popup displayed but the user is not logged out and redirected to external link
     - Version 4.0.39. clicking on external link, no popup displays. User is logged out and redirected to external link


I can  share the screen with you either with skype or MS teams. Please let me know if you need more info.

Thanks

Pearl

From: Nguyen, Pearl Phu PPT [NC]
Sent: December 18, 2020 1:40 PM
To: 'wet-boew/cdts-sgdc' <reply@reply.github.com>; wet-boew/cdts-sgdc <cdts-sgdc@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [wet-boew/cdts-sgdc] popup is not displayed for external link (#198)

I will test and let you know. thanks

**Comment by ahmad-shahid** [comment]
Hi @nguyenpearl , the fix has been deployed on v4.0.39. 
Can you re-test? Thanks

**Comment by nguyenpearl** [comment]
I will do tomorrow. thanks

**Comment by jonnorth** [comment]
@ahmad-shahid It appears this change has broken the existing functionality when using the redirect url and setting display model window = false. The redirect url is not used and the modal window is now always displayed

**Comment by ahmad-shahid** [comment]
@jonnorth I am looking into the displaymodal = false issue. 
When you say the redirect url is not used, if you click yes on the modal, it is not taking you to the redirect url? What is the behaviour?

**Comment by nguyenpearl** [comment]
Hi,

Here is message from my coworker who tested with .net app. We do not test with java yet.



[‎2021-‎01-‎13 10:07 AM]  Toporova, Rimma R [NC]:
in dev in firefox I don't see nothing, in IE I see this java script error:Line: 9
Error: Unable to get property 'msgboxHeader' of undefined or null reference


Popup not display, same as before

[‎2021-‎01-‎13 10:13 AM]  Toporova, Rimma R [NC]:
So it works in Edge and Chrome and does not in Firefox and IE

**Comment by jonnorth** [comment]
> @jonnorth I am looking into the displaymodal = false issue.
> When you say the redirect url is not used, if you click yes on the modal, it is not taking you to the redirect url? What is the behaviour?

@ahmad-shahid We do not display the modal dialog we set displaymodal = false so no modal is displayed. The expected behaviour is when an external link is selected it will redirect to the url specified in the value for the exitUrl. It's now always displaying a modal. Also it seems that the query string parameter was changed from targetUrl to extUrl  in 4.0.39 then back to targetUrl again in an update to v4.0.39

**Comment by nguyenpearl** [comment]
the new build works for .net apps in Edge, Chrome and Firefox. Thanks

**Comment by ahmad-shahid** [comment]
@jonnorth Can you re-test? Thanks

**Comment by jonnorth** [comment]
@ahmad-shahid I've re-tested and it's working as expected now. Thanks 👍
