### ISSUE TITLE
Unable to open a link in a new window

### ISSUE THREAD

**Issue by nguyenpearl** [wet-boew/cdts-sgdc#199]
We are unable to open a link in new window with target="blank"

**Comment by jonnorth** [comment]
We also noticed that this is no longer working. I had previously opened an issue regarding this and at one point I believe it was fixed. See #49

**Comment by StdGit** [comment]
You are right, the exitscript has been retrograded to v4_0_32 behaviour without target_blank.
Instead exitscript has been implemented in wet-boew
https://wet-boew.github.io/wet-boew/demos/exitscript/exitscript-en.html#wb-auto-4
cdts v4_0_39 didn't implement this new feature yet.
We plan to implement it in the next version.
Suggestion: Perhaps you can use the wet-boew version. However you have to disable the call to exitscript
set "exitScript": false,

Could I close the ticket?

**Comment by nguyenpearl** [comment]
Hi this ticket is for version 4.0.39. the newest version, not 4.0.32. Thanks

**Comment by StdGit** [comment]
Version 4.0.39 has the same code than 4.0.32 for the exitscript component.

Could I close the ticket?

**Comment by nguyenpearl** [comment]
One moment please, let us test in both java and .nety app. Will get back to you very soon thanks

**Comment by nguyenpearl** [comment]
We tested with version 4.0.49. When we click on a footer link the popup is not displayed. thanks

**Comment by ahmad-shahid** [comment]
This is issue has now been fixed. Please re-test and let me know if I can close this issue.

**Comment by ahmad-shahid** [comment]
Confirmed to be working (fix part of #198)
