### ISSUE TITLE
CDTS header - language toggle link is missing the classes of the responsive design

### ISSUE THREAD

**Issue by RubyDo** [wet-boew/cdts-sgdc#203]
This is on all CDTS demo pages  e.g. [content page ](https://cenw-wscoe.github.io/sgdc-cdts/GCWeb/samples/content-en.html) (current code points to use of gcweb/v4_0_28/cdts/)

Issue: 
The header is missing for the responsive design text and classes switch  as a result language toggle link appears in full "Français" instead of "FR" on mobile view. 

Missing code is emphasized in **strong below**
`<a lang="fr" href="/fr/services/prestations/ae.html">`                      
`<span **class="hidden-xs"**>Français</span>`
**`<abbr title="Français" class="visible-xs h3 mrgn-tp-sm mrgn-bttm-0 text-uppercase">fr</abbr>`**
`  </a>`

**Comment by ahmad-shahid** [comment]
Will be resolved by the same fix for #135

**Comment by ahmad-shahid** [comment]
This has been fixed.
