### ISSUE TITLE
Canada.ca theme: Navigation landmarks missing unique accessible names

### ISSUE THREAD

**Issue by szet0018** [wet-boew/cdts-sgdc#204]
This issue relates to issue 146 which is on the Application template.
https://github.com/wet-boew/cdts-sgdc/issues/146

There is an AXE error on the Canada.ca theme template.
https://cenw-wscoe.github.io/sgdc-cdts/GCWeb/samples/content-en.html

**Issue Description**
Landmarks must have a unique role or role/label/title (i.e. accessible name) combination

**Element location**
body > nav
Element source
`<nav>`

**To solve this violation, you need to...**
Fix the following:
The landmark must have a unique aria-label, aria-labelledby, or title to make landmarks distinguishable

Related nodes:
#wb-auto-2
#wb-bc
.wb-navcurr
.col-md-9

My Suggested Solution:
- Where available, the `<nav>` should have an aria-labelledby that references the heading for that navigation section
- Add an id to the headings so they can be referenced by aria-labelledby
- When there is no heading, then an aria-label can be added

Example Code
```
<nav aria-label="Skip Links">
<ul id="wb-tphp" class="wb-init wb-disable-inited">
<li class="wb-slc"><a class="wb-sl" href="#wb-cont">Skip to main content</a></li>
<li class="wb-slc visible-sm visible-md visible-lg"><a class="wb-sl" href="#wb-info">Skip to "About government"</a></li>
<li class="wb-slc"><a class="wb-sl" rel="alternate" href="?wbdisable=true">Switch to basic HTML version</a></li>
</ul>
</nav>

```
```
<nav aria-labelledby="menu" class="gcweb-menu wb-init gcweb-menu-inited" typeof="SiteNavigationElement" id="wb-auto-2">
<div class="container">
<h2 id="menu" class="wb-inv">Menu</h2>
```

**Comment by ahmad-shahid** [comment]
The `nav` elements now have aria-labelledby and aria-label as per the suggestion above.
