### ISSUE TITLE
Application template - Skip links not wrapped in nav element

### ISSUE THREAD

**Issue by szet0018** [wet-boew/cdts-sgdc#206]
There is a AXE error of "All page content must be contained by landmarks" on the Application template.

https://cenw-wscoe.github.io/sgdc-cdts/GCWeb/appTop/apptop-en.html
The skip links in the application template are not wrapped in a nav element.

```
<ul id="wb-tphp" class="wb-init wb-disable-inited">
<li class="wb-slc"><a class="wb-sl" href="#wb-cont">Skip to main content</a></li>
<li class="wb-slc visible-sm visible-md visible-lg"><a class="wb-sl" href="#wb-info">Skip to "About this Web application"</a></li>
<li class="wb-slc"><a class="wb-sl" rel="alternate" href="?wbdisable=true">Switch to basic HTML version</a></li>
</ul>

```
https://cenw-wscoe.github.io/sgdc-cdts/GCWeb/samples/content-en.html
They should follow the Canada.ca template, which does wrap the skip links in a nav

```
<nav>
<ul id="wb-tphp" class="wb-init wb-disable-inited"><li class="wb-slc"><a class="wb-sl" href="#wb-cont">Skip to main content</a></li>
<li class="wb-slc visible-sm visible-md visible-lg"><a class="wb-sl" href="#wb-info">Skip to "About government"</a></li>
<li class="wb-slc"><a class="wb-sl" rel="alternate" href="?wbdisable=true">Switch to basic HTML version</a></li>
</ul></nav>
```

**Comment by ahmad-shahid** [comment]
Fixed. Skip links are now wrapped in a nav.

**Comment by ahmad-shahid** [comment]
![image](https://user-images.githubusercontent.com/52757738/140416277-e505b8f0-f042-4ec9-9806-7126d1d19ea5.png)
