### ISSUE TITLE
Leaving Secure Site

### ISSUE THREAD

**Issue by jonjones** [wet-boew/cdts-sgdc#207]
The leavingSecureSiteWarning has been changing over that last few releases and it's at a point where I am not sure it quite makes sense. As it stands now on the live version, when a link is actioned, you get the modal window (if its set to true) without question. Since our application is public facing, we warn the user that if they leave their form they will lose the information they have entered and their session will expire. This part works great, however, this becomes an issue when the actioned link is of target="_blank" variety. In this case, we do not expire the session and the user does not lose the data yet that same message is displayed with an added (appended) messages that states the link will open in a new window (or tab). We need to either have a separate message for this case or have no pop up altogether for target="_blank" links.

**Comment by ahmad-shahid** [comment]
Hi, we will go with your second suggestion and add the option of allowing you to turn off the modal dialog for links that open in a new window.

**Comment by ahmad-shahid** [comment]
Hello, with the release of v4.0.43, you can now set 'displayModalForNewWindow' to false, in order to have no pop up for target="_blank" links
