### ISSUE TITLE
The name 'WebTemplateCore' does not exist in the current context

### ISSUE THREAD

**Issue by 4rsood** [wet-boew/cdts-sgdc#214]
I am getting the error "The name 'WebTemplateCore' does not exist in the current context" while trying to implement Intranet.canada.ca theme.   The application runs fine on my local VM but this error happens when I deploy the application to our dev environment.   I am using .NET Framework 4.8 and GoC.WebTemplate version v4_0_39.  I have attached the error message details.

Thank You,

[error.txt](https://github.com/wet-boew/cdts-sgdc/files/6688169/error.txt)

**Comment by ahmad-shahid** [comment]
Issue resolved (discussed via email).
