### ISSUE TITLE
Application template menubar accessibility issues

### ISSUE THREAD

**Issue by szet0018** [wet-boew/cdts-sgdc#215]
https://cenw-wscoe.github.io/sgdc-cdts/GCWeb/appTop/apptop_all-en.html

`<ul class="list-inline menu" role="menubar">`

JAWS screen reader issue with the menubar
- JAWS screen reader is not reading the name of the parent menuitem with the submenus e.g. "Second section"
- No issues with NVDA screen reader though, which does read "Second section"

AXE founds issues with the menubar
- AXE is finding issues with the parent/child relationships with the list elements

Suggested Solution
- Should ideally follow the WAI-ARIA Authoring Practices for Navigation Menubar Example
- See: https://www.w3.org/TR/wai-aria-practices-1.1/examples/menubar/menubar-1/menubar-1.html

**Comment by ahmad-shahid** [comment]
Hello, there was a new deployment done and the code is following the W3C guidelines. Can you please test again?

**Comment by szet0018** [comment]
I tested with JAWS 2020 on Chrome and the reader correctly reads the menubar now.

I'm still getting AXE issues though

Required ARIA children role not present: group, menuitemradio, menuitem, menuitemcheckbox
Required ARIA parents role not present: menu, menubar, group
List item does not have a <ul>, <ol> parent element without a role, or a role="list"

Adding role="presentation" to the <li> in the menubar fixes these issues for me.
