### ISSUE TITLE
Issues with 4.0.43 Update

### ISSUE THREAD

**Issue by sgdowney** [wet-boew/cdts-sgdc#216]
Problem Found in
Web Templates Version:* 2.4.0
CDTS Version: 4.0.43
Template:* MVC
Environment:* AKAMAI
Master/Layout: Application
Additional settings:

Problem Description:
The link generated to switch to Basic HTML Version has invalid URL parameters when the original page link contains URL parameters.
Original Page Link
https://int16-ssl.services.gc.qat/irs-sdi/interdec/infodebase-basicinfo/preambule-preamble.aspx?wn=0&fwc=0
Generated Link
https://int16-ssl.services.gc.qat/irs-sdi/interdec/infodebase-basicinfo/preambule-preamble.aspx?wn=0&#38;fwc=0&#38;wbdisable=true

**Comment by ahmad-shahid** [comment]
This issue was opened under the WET repo - https://github.com/wet-boew/wet-boew/issues/9139

Closing this issue.
