### ISSUE TITLE
Alert not showing the background-color

### ISSUE THREAD

**Issue by sgdowney** [wet-boew/cdts-sgdc#217]
Originally reported in GC/Code Web Templates repository.
Alert not showing the background-color

Open

Alert not showing the background-color
Problem Found in

Version:* v4_0_43 GoCWebTemplate v2.4.0
Template:* CoreMVC
Problem Description:

The alert component seems to not be displaying the appropriate background color this issue can be seen on the following page: https://wet-boew.github.io/GCWeb/components/components-en.html

Removing the background-color: inherit; from the CSS of the .alert class makes the alert component look like the following image which brings the question is the alert having a transparent background the expected result or is this a bug?

![AlertBackgroundColor](https://user-images.githubusercontent.com/5131107/126004684-fe2a8654-aa2b-4eb0-b4f0-ee14adb00ab5.png)

**Comment by ahmad-shahid** [comment]
This issue was opened under the WET repo - https://github.com/wet-boew/wet-boew/issues/9138

Closing this issue.
