### ISSUE TITLE
Add Subresource_integrity to wet-en/fr.js files

### ISSUE THREAD

**Issue by ahmad-shahid** [wet-boew/cdts-sgdc#226]
We need to secure our download.
https://developer.mozilla.org/fr/docs/Web/Security/Subresource_Integrity

Transferred from: https://gccode.ssc-spc.gc.ca/iitb-dgiit/nw-ws/sgdc-cdts/-/issues/164

- [x] Part 1: SRI hash generation module
- [x] Part 2: generation of hashes for internal files.
- [x] Part 3: Implementation of internal SRI in template functions
- [x] Part 4: Generation of hashes for public files
- [ ] Part 5: Include SRI hashes in static fallback flies?
- [ ] Part 6: Make sure CORS header is setup on all servers before enabling this feature

**Comment by ahmad-shahid** [comment]
This may cause an issue if one updates CDTS but forgets to update the integrity string. (will require further discussion)

**Comment by plup2** [comment]
As discussed, part 2 shouldbe handled in the "preprocess" phase of EJSModuleGenerate module so we end up with something like this:
`<link rel="stylesheet" href="<%- wet.builder.environment(pr.cdnEnv) %>wet-boew/css/theme.min.css" <% if (pr.sriEnabled) { %>integrity="<^- sriHash('public/gcweb/cdtsfixes.css') ^>" crossorigin="anonymous"<% } %>>`

**Comment by plup2** [comment]
@kmaddocks-gc  Sub Resource Integrity is in the works for CDTS:
- The CDTS itself should support SRI in its next release (or the one after that if we have an emergency)
- The .NET and Java WebTemplate should support SRI in their release following the CDTS "SRI" release 
- For clients using CDTS directly and wanting to have SRI, a file SRI-INFO.md will be generated containing the hashes of CDTS public files
- With that done, there will be a few scripts coming from WET library that still won't have the `integrity` attribute for a while. They will have to fix it in WET but will not necessarily be trivial.  I have opened an issue in WET: wet-boew/wet-boew#9543
