### ISSUE TITLE
content type mime type no sniffing tag security

### ISSUE THREAD

**Issue by ahmad-shahid** [wet-boew/cdts-sgdc#234]
We need to set the right content type in cdts (See accept in request header), and we need to know the configuration of  mime type in the server and perhaps it should return a nosniff

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept
https://www.denimgroup.com/resources/blog/2019/05/mime-sniffing-in-browsers-and-the-security-implications/
https://webhint.io/docs/user-guide/hints/hint-content-type/#page-heading

Transferred from: https://gccode.ssc-spc.gc.ca/iitb-dgiit/nw-ws/sgdc-cdts/-/issues/186

**Comment by plup2** [comment]
@ahmad-shahid Now that the content-type on the new servers have been double-checked, does that mean we can close this issue?

**Comment by ahmad-shahid** [comment]
Yes, you're right. I'll close this now.
