### ISSUE TITLE
Review/cleanup extra repos following restructure

### ISSUE THREAD

**Issue by plup2** [wet-boew/cdts-sgdc#241]
The following 3 repositories were found while doing project re-structure.  Should be reviewed and what is not needed should be cleaned up.

(Descriptions are from the pre-restructure README.md)

##### [cdts-sgdc-cdn](https://github.com/wet-boew/cdts-sgdc-cdn)

Used to host the `dist` folder to be able to pull to different servers. [Travis.CI](https://travis-ci.org/wet-boew/cdts-sgdc) is used to build and then deploy to these secondary repositories within the coffee scripts. Will create a branch with the current version number. And tags for releases. 

##### [cdts-sgdc-dist](https://github.com/wet-boew/cdts-sgdc-dist)

Not sure what this is for but WET has it. Might get rid of it, might keep it. WET uses to host all their working files.

##### [cdts-sgdc-releases](https://github.com/wet-boew/cdts-sgdc-releases)

Holds all the releases so that servers can pull from this repository onto the CDNs.

A 4th one has also been found while browsing through wet-boew's repos:

##### [cdts-sgdc-docs](https://github.com/wet-boew/cdts-sgdc-docs)

Empty, meant for docs? Replacement/complete to https://github.com/cenw-wscoe/sgdc-cdts ?

**Comment by ahmad-shahid** [comment]
The repositories have been archived. They will be deleted at the completion of the milestone.

**Comment by plup2** [comment]
`cdts-sgdc-dist` will be repurposed for cloud releases to the WCMS environment

**Comment by plup2** [comment]
I updated the description of the issue to include a 4th repo

**Comment by ahmad-shahid** [comment]
The 4h repo `cdts-sgdc-docs` has now been archived. It will be deleted at the completion of the milestone.

**Comment by ahmad-shahid** [comment]
cdts-sgdc-cdn has been renamed to cdts-JavaTemplates
cdts-sgdc-docs has been renamed to cdts-DotNetTemplates

**Comment by ahmad-shahid** [comment]
`cdts-sgdc-releases` has been renamed to `cdts-sgdc-react`

All repositories have now been repurposed.
