### ISSUE TITLE
wet-en.js returning 404

### ISSUE THREAD

**Issue by eniangab** [wet-boew/cdts-sgdc#262]
We use wet toolkit for our application MITRACK, we've been having this issue on and off starting around 13:30 on 2021-09-09
Could you please help, we've never seen this before:

Failed to load resource: the server responded with a status of 404 (Not Found) wet-en.js:1 
Failed to load resource: the server responded with a status of 404 (Not Found) soyutils.js:1 
Failed to load resource: the server responded with a status of 404 (Not Found) wet-en.js:1 

![image](https://user-images.githubusercontent.com/68653838/132756713-71a90826-1890-451d-8ad6-862b3cbcb0a8.png)

**Comment by duboisp** [comment]
@ahmad-shahid see the above request. Thanks

**Comment by ahmad-shahid** [comment]
There was a fix that was put in this morning. Can you confirm if you are still seeing this error?

**Comment by ghost-girl** [comment]
@ahmad-shahid The error still occurs, all resources for the intranet template coming from https://ssl-templates.services.gc.ca/ appear to return 404's.

**Comment by ghost-girl** [comment]
@ahmad-shahid Template appears to load correctly but after doing a hard refresh CTRL+F5 all resources return 404's for Intranet template.

**Comment by ahmad-shahid** [comment]
@ghost-girl thank you. The team is investigating. As soon as there is an update, I'll provide it here.

**Comment by eniangab** [comment]
Latest test at 12:25PM seems to be ok.
I'll report  back if it shows up again.

Thank you.
Asuquo Eniang

Programmer-Analyst, Digital Services Directorate - Solution Center - Marine Portfolio
Transport Canada / Government of Canada
***@***.******@***.***> / Tel: 613-447-2976 / TTY: 1-888-675-6863

Programmeur-analyste, direction générale des services numériques - centre des solutions - portefeuille maritime
Transports Canada / Gouvernement du Canada
***@***.******@***.***> / Tél. 613-447-2976 / ATS : 1-888-675-6863

**Comment by ahmad-shahid** [comment]
This issue should now be fixed. There shouldn't be any 404s. Thanks.
