### ISSUE TITLE
nsd.js is buggy

### ISSUE THREAD

**Issue by StdGit** [wet-boew/cdts-sgdc#286]
This script is buggy

**Comment by ahmad-shahid** [comment]
Hello, what is this script?

**Comment by StdGit** [comment]
You can find it here.
https://iservice.prv/fra/si/securite/categorisation/outil-categorisation.shtml
It is using cdts

![image](https://user-images.githubusercontent.com/5129874/137008846-25a438f8-9881-47bc-ae6b-273f700e3d0b.png)
