### ISSUE TITLE
Soy/Closure Template dependency

### ISSUE THREAD

**Issue by shawnthompson** [wet-boew/cdts-sgdc#3]
Copied from https://gitlab.com/shawnthompson/sgdc-cdts/issues/3

Open by @nschonni

Is this a requirement of a current server-side implementation that is depended on by implmentors, or is it just an intermediate build tool that spits out some compiled files?
I'm wondering since you're switching from a Java to Node build setup, if taking a dependency on this templating language is still needed, or if should be switched to something else? EX: WET uses Handlebars for templating, UK.Gov uses Nunjucks

**Comment by shawnthompson** [comment]
Just switching the building tool. Not the language. That will be in version 2.0. Creating our own.

https://gitlab.com/esdc-edsc/next_centrally_deployed_templates_solution

**Comment by timarney** [comment]
It would be good to note in the Readme that a Java runtime is required for the templates to compile.

The current build step fails if you don't have a Java runtime installed.

**Comment by shawnthompson** [comment]
Shoot I forgot about that because it was already installed! Thanks @timarney

**Comment by StdGit** [comment]
Je crois que le SGDC devrait utiliser quelque chose d'autres que closure-templates (SoyToJsSrcCompiler.jar) car Google ne le supporte plus à l'externe.
I think cdts should use something else than  closure-templates (SoyToJsSrcCompiler.jar) since google doesn't support it externally.

> https://github.com/google/closure-templates
> Closure Templates is widely used and well maintained internally at Google but does not currently have staffing to support the open source release. As such this project is mostly a 'code dump' and support is minimal. For certain issues, like build integration we are in an especially bad position to offer support.

**Comment by ahmad-shahid** [comment]
We have moved on from soy. Therefore, I will close this issue.
