### ISSUE TITLE
input type hidden _charset_ for the search form

### ISSUE THREAD

**Issue by laurencechavet** [wet-boew/cdts-sgdc#394]
Hi

When downloading the versions of the CDTS (up to the latest [v4.0.44 - Canada.ca theme](https://cenw-wscoe.github.io/sgdc-cdts/GCWeb/static/Gcwebstatic-v4_0_44.zip)), I see in the top_en.html, line 21 the input type=hidden name=_charset_ for the form to search.
`<input type="hidden" name="_charset_" value="UTF-8">`

This creates a HTML validation error as per the [spec for hidden state](https://html.spec.whatwg.org/multipage/input.html#hidden-state-(type=hidden)), that specifies "If the name attribute is present and has a value that is an ASCII case-insensitive match for "_charset_", then the element's value attribute must be omitted."

We can see this is not part of the WET template but is only present in the CDTS. As this makes all our applications fail the validation, would it be possible to remove it and to adjust as the WET. Or will this create an encoding issue?

Thanks

**Specifications**
![specs4_10_5_1_1](https://user-images.githubusercontent.com/65306416/149837275-c1ff6891-1973-43ed-b059-a00e449465a6.jpg)

**Canada.ca**
![canada_ca](https://user-images.githubusercontent.com/65306416/149837278-3da276c9-f4a7-46c7-b21c-e26b8cd1db0d.jpg)

**CDTS 4.0.44**
![cdts4_0_44](https://user-images.githubusercontent.com/65306416/149837279-4487b5c3-f54f-42d9-9d15-82c34b84882f.jpg)

**Comment by plup2** [comment]
Not sure why this wasn't caught by our own validation.

@ahmad-shahid As discussed, I tested with our windows-1252 test app and confirmed that this `value` attribute is ignored by the browser anyway and the charset of the page is sent no matter what, so we can/should definitely get rid of the `value` attribute for this input.  **BUT** we should also add `accept-charset="utf-8"` to the `form` element to make sure the data will be submitted as UTF-8 no matter the encoding of the page.
