### ISSUE TITLE
Errors when trying to load mediatcontrols.html - CORS request rejected from canada.ca

### ISSUE THREAD

**Issue by GarthMartin** [wet-boew/cdts-sgdc#400]
We have started getting errors all of a sudden with pages that have embedded videos.   The call to https://www.canada.ca/etc/designs/canada/cdts/gcweb/v4_0_32/assets/mediacontrols.html is getting rejected by canada.ca saying 
Access to XMLHttpRequest at 'https://www.canada.ca/etc/designs/canada/cdts/gcweb/v4_0_32/assets/mediacontrols.html' from origin 'https://pcis-sipc.tbs-sct.gc.ca' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.

I checked with our firewall guys and it's not being blocked on our end.

Does anyone know if canada.ca has changed their CORS configuration, or who I could contact to figure out what they changed?

Thanks,

Garth

**Comment by ahmad-shahid** [comment]
Hello, we are not aware of any changes. I'll try to find out and get back to you.

**Comment by ahmad-shahid** [comment]
Hello, just an update: as far as the CDTS files go, canada.ca has not changed the CORS configuration (all our files confirm CORS header).
