### ISSUE TITLE
Creating tables dynamically using jQuery does not work in CDTS v4_0_44

### ISSUE THREAD

**Issue by adam2** [wet-boew/cdts-sgdc#434]
Hi,

I've found a bug with the CDTS v4_0_44 templates.  I'm not sure if this bug is in CDTS or if it is in WET.  We found it when attempting to upgrade our sites to the v4_0_44 templates.

The issue is that when using jQuery to dynamically create an HTML table, it doesn't work in CDTS v4_0_44.  Some <row> and <td> elements you would expect to be added are not being added.  It's as if the jQuery append function isn't working.  It's difficult to explain, so I made two demo pages which make the problem obvious.  Please see the attached files.  The code in both pages is identical, except for the CDTS URL.  The JavaScript works properly in v4_0_43 but not in v4_0_44.

Please let me know if you have any questions.

Thanks,
Adam
[cdts-4043.html.txt](https://github.com/wet-boew/cdts-sgdc/files/8127195/cdts-4043.html.txt)
[cdts-4044.html.txt](https://github.com/wet-boew/cdts-sgdc/files/8127197/cdts-4044.html.txt)

**Comment by ahmad-shahid** [comment]
Hello, it looks like this issue is in WET. To test, I changed the file **wet-boew.min.js** to version v4.0.43 but kept the version of CDTS the same and the table issue resolved. It seems that a bug came about somewhere in between WET version v4.0.43 and v4.0.44.5.

The WET team will be able to assist. An issue can be created here.: https://github.com/wet-boew/wet-boew/issues

**Comment by duboisp** [comment]
See my answer here: https://github.com/wet-boew/wet-boew/issues/9293#issuecomment-1054968565

This is not an issue, it is intentional by design.

Cheers

**Comment by adam2** [comment]
This "intentional, by design" decision break a lot of our JavaScript code.  Probably it affects many other departments as well, which may not have noticed or commented on the issue this far.  CDTS 4.0.43, which still works properly, is still the "run" version.  I would expect more issues logged in the future for breaking basic jQuery functionality.

**Comment by duboisp** [comment]
For the record.

The change made at jQuery was a security patch to prevent XSS attack.

We are available to discuss more during our weekly Tuesday afternoon live support. Or alternatively you can find my contact information in GCDirectory and we will coordinate a meeting to discuss further.

**Comment by adam2** [comment]
Since this is clearly a WET bug, and not a CDTS bug, I suggest closing this one.

Thank you ahmad-shahid for looking at it.
