### ISSUE TITLE
WET version hosted on CDTS

### ISSUE THREAD

**Issue by sgdowney** [wet-boew/cdts-sgdc#441]
What is the specific WET version supported by CDTS?  There are multiple releases for 4.0.44.
4.0.44
4.0.44.1
4.0.44.2
4.0.44.3
4.0.44.4
4.0.44.5

**Comment by ahmad-shahid** [comment]
Hello, CDTS is currently supporting WET v4.0.44.5.

You can find this information summarized on our CDTS documentation site here: 

https://cenw-wscoe.github.io/sgdc-cdts/docs/index-en.html#Current_CDTS_supported_versions
