### ISSUE TITLE
AjaxControl Toolkit - CalendarExtender: Error

### ISSUE THREAD

**Issue by viktorw1** [wet-boew/cdts-sgdc#444]
I am currently using the latest CDTS templates in my webform application, GoC.WebTemplate.Components, GoC.WebTemplate.Components.Framework and GoC.WebTemplate.WebForms, but experiencing a problem when trying to use the AjaxControl toolkit control CalendarExtender.

MasterPageFile="~/GoC.WebTemplate/GoCWebTemplate.Application.Master"
<asp:Label runat="server" ID="lblLoginDate" for="startdate" CssClass="labelText" Text="<%$ Resources:Common, lblDateFrom %>" />
<asp:TextBox runat="server" class="form-control ddl" ClientIDMode="Static" autocomplete="off" ID="txtFromDate" Text="<%$ Resources:Common, lblDatePlaceholder %>"/>
<ajaxToolkit:CalendarExtender ID="CalendarFrom" PopupButtonID="imgPopup" runat="server" TargetControlID="txtFromDate" Format="yyyy/MM/dd"> </ajaxToolkit:CalendarExtender> 

There was an initial error that the head tag was missing ‘runat=”server”’, so I added it to the masterpage template “<head runat="server">” (no other modifications have been done to the masterpage), but then I received an additional error:

The Controls collection cannot be modified because the control contains code blocks (i.e. <% ... %>).
   at System.Web.UI.ControlCollection.Add(Control child)
   at AjaxControlToolkit.ToolkitResourceManager.RegisterCssReferences(Control control)
   at AjaxControlToolkit.ExtenderControlBase.OnLoad(EventArgs e)
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

I googled it and tried some of the solutions, ex. asp:PlaceHolder on the descendant webform but to no avail, do you have a fix for this?

In addition I also use the ajaxToolkit:FilteredTextBoxExtender control and it works fine, so it seems to only fail on the Calendar extender control.

Any help would be much appreciated.

Thank you,

Will

**Comment by viktorw1** [comment]
In order to get the CalendarExtender to work, I had to add the asp:PlaceHolder in the master page and add runat="server" in the head tag (GoC.WebTemplate.WebForms.WebTemplateMasterPage), but not sure what the impact would be as I didn't build this page. 

Can the CDTS team confirm this is OK to do? 

Please see code below.

Thanks

<head runat="server">
        <meta charset="utf-8"/>
        
        <title><%= WebTemplateModel.Render.HeaderTitle() %></title>
        <asp:PlaceHolder runat="server">
            <meta content="width=device-width,initial-scale=1" name="viewport"/>
            
            <script type="text/javascript" src="<%= string.Concat(WebTemplateModel.CDNPath, "soyutils.js")  %>"></script>
            <script type="text/javascript" src="<%= string.Format(System.Globalization.CultureInfo.InvariantCulture, "{0}wet-{1}.js", WebTemplateModel.CDNPath, WebTemplateModel.TwoLetterCultureLanguage)  %>"></script>
            <noscript>
                
                <%= WebTemplateModel.LoadStaticFile("refTop.html") %>
            </noscript>
                
            <script type="text/javascript">
                document.write(wet.builder.refTop(<%= WebTemplateModel.Render.RefTop(isApplication: true) %>));
            </script>

            <%= WebTemplateModel.Render.HtmlHeaderElements() %>
            
            
        </asp:PlaceHolder>
    </head>

**Comment by ahmad-shahid** [comment]
Hello ideally we encourage that the template files should not be touched but if this is the only solution and there is no other workaround to solve your error, then it should be okay (for now).

This will be an issue for future versions. Please keep in mind that you will have to make this change every time you update to a newer version of Webforms because you should have the latest master templates.

**Comment by viktorw1** [comment]
Thanks for your help Ahmad.
