### ISSUE TITLE
Bug - Global search not configure properly

### ISSUE THREAD

**Issue by delisma** [wet-boew/cdts-sgdc#445]
## Describe the bug
When using the global search on a page with the CDTS template, the submit points to https://recherche-search.gc.ca instead of https://www.canada.ca/en/sr/srb.html and produce the error display below.

<img width="1745" alt="image" src="https://user-images.githubusercontent.com/2599251/157513406-2e4c1394-4b7d-4b87-80b2-1ab61f0501fb.png">

## To Reproduce
Steps to reproduce the behaviour:
1. Go to '.[Laws and regulations pages - Canada.ca template](https://design.canada.ca/recommended-templates/laws-regulations-pages.html)'
2. Click on the '.search' input in the main header
3. Type any keyword (i.e test)
4. Cick the search button
5. See error

**Comment by ahmad-shahid** [comment]
Hello, I don't think that site is using CDTS. You can report this issue through the "Report a problem on this page" button on the page you provided.
