### ISSUE TITLE
Change release repo to use submodules instead of copy of files

### ISSUE THREAD

**Issue by shawnthompson** [wet-boew/cdts-sgdc#47]
In this repo https://github.com/wet-boew/cdts-sgdc-releases we are deploying copies of the releases into it.

Controlled in the [Gruntfile.coffee @ L325](https://github.com/wet-boew/cdts-sgdc/blob/master/Gruntfile.coffee#L325):

Might be better to use [submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules) instead.

Similar to how WET does it in their [themes-dist](https://github.com/wet-boew/themes-dist) repo

CC: @duboisp

**Comment by patricehernert** [comment]
@shawnthompson Could you confirm this issue is still valid for version 4.0.39 ? Thanks.

**Comment by StdGit** [comment]
@patricehernert yes it is still valid.

**Comment by ahmad-shahid** [comment]
Project was restructured and the we will keep the existing process in place.
