### ISSUE TITLE
A link on a sample page no longer valid

### ISSUE THREAD

**Issue by plup2** [wet-boew/cdts-sgdc#470]
First good news, our shcedule TestLink run ran this morning successfully and returned no error.

But the run done on merge to master just failed with "csszengarden.com" no longer working. (https://github.com/wet-boew/cdts-sgdc/runs/5628694275?check_suite_focus=true).  I checked both from work proxy and home computer and it seems to be correct. We should probably changed our external site to something less exotic like google or microsoft home page.

**Comment by ahmad-shahid** [comment]
I remember that site going down a while back as well. Definitely time to change it.
