### ISSUE TITLE
Ignore dist directory in gitignore and include in npmignore

### ISSUE THREAD

**Issue by shawnthompson** [wet-boew/cdts-sgdc#5]
Copied from https://gitlab.com/shawnthompson/sgdc-cdts/issues/1

Open by @nschonni

Checking in the build files will likely get messy. You can ignore the files from git, but include them as part of the NPM published tarball using npmignore.

**Comment by shawnthompson** [comment]
Added `dist` to the gitignore... @nschonni remind me again what I should put in the npmignore and what it does?

**Comment by pabrams** [comment]
I think you just need to add the file, and not exclude dist in the file.  Otherwise npm uses the gitignore.

https://github.com/sinonjs/sinon-test/pull/62

**Comment by nschonni** [comment]
You use (and partially duplicate I guess) with the `.npmignore` if you want things included when you publish your NPM package (like maybe built copies of files) but you don't want included in your git history.

**Comment by shawnthompson** [comment]
I think I read something about deploying from TravisCI and it reading your gitignore so there's something I will need to do to deploy my `dist` folder.

**Comment by shawnthompson** [comment]
deploy and build worked so I think we can close this. If I'm wrong please reopen it.
