### ISSUE TITLE
Update to Adobe Analytics with custom code.

### ISSUE THREAD

**Issue by TTVXStarWake** [wet-boew/cdts-sgdc#50]
Moved from GCCode: https://gccode.ssc-spc.gc.ca/iitb-dgiit/nw-ws/sgdc-cdts/issues/147

@shawnthompson 

Would like to add a custom variable into the AA code that would allow developers to add in their own URL to the Analytics versioning. Principle Publisher will be updating the AA version often (about every 6 months). but adding a custom rule, they can update their own. To stop breaking change we need to keep the versions 1 and 2 as is but moving forward they can add their own path.

**script src="//assets.adobedtm.com/[variable]**

https://gccode.ssc-spc.gc.ca/iitb-dgiit/nw-ws/sgdc-cdts/blob/v.1.0.1/app/cls/WET/gcweb/v4_0_32/cdts/uncompiled/wet-en.soy#L72

```
document.write(wet.builder.refTop({
    "webAnalytics" : [{
        "custom" : "caacec67651710193d2331efef325107c23a0145/satelliteLib-78cf42deb149c9766cbaaa6151e252b9b67c0200-staging"
    }]
}));
```

**Comment by patricehernert** [comment]
@MaximMartel Could you confirm this issue is still valid for version 4.0.39 ? Thanks.

**Comment by StdGit** [comment]
Need a demo without document.write

**Comment by ahmad-shahid** [comment]
Adobe analytics has been addressed. For issues regarding document.write, please see #55
