### ISSUE TITLE
Escaping HTML and JS

### ISSUE THREAD

**Issue by MaximPerry** [wet-boew/cdts-sgdc#52]
Moved from GC Code: https://gccode.ssc-spc.gc.ca/iitb-dgiit/nw-ws/sgdc-cdts/issues/30

From @shawnthompson : 

As noted in an email "contactLink override in CDTS v4_0_26".

Google closure is not escaping JS or HTML

On this page: 

https://ssl-templates.services.gc.ca/app/cls/WET/gcweb/v4_0_26/cdts/appTop/msca-footer.shtml 

``HTML
		<script type="text/javascript">
			var defFooter = document.getElementById("def-footer");
			defFooter.outerHTML = wet.builder.appFooter({
				cdnEnv: cdnEnvVar,
				showFeatures: false,
				contactLink: "javascript:(function(){window.open('http://www.google.ca/')})()",
				termsLink: "#",
				privacyLink: "#"
			});
		</script>
``

**Comment by MaximPerry** [comment]
From @shawnthompson : 
I found this
https://developers.google.com/closure/templates/docs/security

**Comment by MaximPerry** [comment]
From @shawnthompson : 
Still a problem.
Open a Github issue, then close this issue.

**Comment by patricehernert** [comment]
@MaximPerry Could you confirm this issue is still valid for version 4.0.39 ? Thanks.

**Comment by StdGit** [comment]
Besoin de clarifications
Google template ajoute soy$$escapeHtml donc il escape les paramètres.

Need clarifications
Google template add soy$$escapeHtml so it escape parameters.

**Comment by ahmad-shahid** [comment]
With EJS, everything was set to be escaped except for URL parameters. Closing this issue.
