### ISSUE TITLE
Create appTop templates for GCIntranet

### ISSUE THREAD

**Issue by MaximPerry** [wet-boew/cdts-sgdc#53]
Moved from GC Code : https://gccode.ssc-spc.gc.ca/iitb-dgiit/nw-ws/sgdc-cdts/issues/36

From @shawnthompson : 

Still needs to be done.

**Comment by patricehernert** [comment]
@MaximPerry Could you confirm this issue is still valid for version 4.0.39 ? Thanks.

**Comment by StdGit** [comment]
un canevas  .appTop existe dans wet-en/fr.soy
---
A template .appTop exist in wet-en/fr.soy
