### ISSUE TITLE
GCWeb: revert data-wb-ajax in menu

### ISSUE THREAD

**Issue by MaximPerry** [wet-boew/cdts-sgdc#54]
Moved from GC Code : https://gccode.ssc-spc.gc.ca/iitb-dgiit/nw-ws/sgdc-cdts/issues/42

From @shawnthompson : 

Related to: #40

Commit: 9fa36892a1859f4d80382ac534633b2311699def

WET Issue: https://github.com/wet-boew/wet-boew/issues/8241

**Comment by patricehernert** [comment]
@MaximPerry Could you confirm this issue is still valid for version 4.0.39 ? Thanks.

**Comment by StdGit** [comment]
WET Issue: wet-boew/wet-boew#8241 est fermée

Nous avons besoin d'un exemple et de la documentation comme
https://cenw-wscoe.github.io/sgdc-cdts/GCWeb/appTop/apptop_custommenu-en.html

wet-en.soy aura besoin d'être ajusté

Pour tester vous pouvez inclure le code suivant dans http://127.0.0.1:8080//app/cls/WET/gcweb/v4_0_39/cdts/samples/breadcrumbs-en.shtml

> `<div id="def-top">
> 	
> 	
> </div>
> 
> <script>
> 	var defTop = document.getElementById("def-top");
> 	defTop.outerHTML = wet.builder.appTop({
> 		"cdnEnv": "esdcprod",
> 		"appName": [{"text": "Application name", "href": "#"}],
> 		"lngLinks": [{"lang": "fr",	"href": "apptop_custommenu-fr.shtml", "text": "Français"}],
> 		"menuPath": "https://cdn.canada.ca/gcweb-cdn-live/sitemenu/sitemenu-en.html"
> 	});
> </script>`

WET Issue: wet-boew/wet-boew#8241 is closed

we need a sample and documentation like
https://cenw-wscoe.github.io/sgdc-cdts/GCWeb/appTop/apptop_custommenu-en.html

wet-en.soy needs to be adjusted

To test you can include previous code into http://127.0.0.1:8080//app/cls/WET/gcweb/v4_0_39/cdts/samples/breadcrumbs-en.shtml

**Comment by ahmad-shahid** [comment]
This is a WET issue which was fixed and closed. Closing this issue.
