### ISSUE TITLE
Replace document.write

### ISSUE THREAD

**Issue by MaximPerry** [wet-boew/cdts-sgdc#55]
Moved from : https://gccode.ssc-spc.gc.ca/iitb-dgiit/nw-ws/sgdc-cdts/issues/47

From @shawnthompson : 

Related to
https://gccode.ssc-spc.gc.ca/GOCWebTemplates/DotNetTemplates/issues/183

**Comment by patricehernert** [comment]
@MaximPerry Could you confirm this issue is still valid for version 4.0.39 ? Thanks.

**Comment by ahmad-shahid** [comment]
The fix for this issue has been deployed as part of v4.0.46. Closing this issue.
