### ISSUE TITLE
Questions concerning the CDTS

### ISSUE THREAD

**Issue by MaximMartel** [wet-boew/cdts-sgdc#56]
Moved from GCCode: https://gccode.ssc-spc.gc.ca/iitb-dgiit/nw-ws/sgdc-cdts/issues/146

@StdGit

rami.elhayek@servicecanada.gc.ca, Tél.: 819-654-0362
Hello,

I am currently tasked to modernise a web based project to a .NET MVC C# application.
A part of this initiative is to work with the most modern version of the CDTS. There are a couple of questions that I have concerning the template in general:

1-	After updating the  GoC.WebTemplate-Components from 1.30.1 to 1.31.2, it appears that the GCTools link as been replaced with four links. It also seems that the text ESDC/SC IntraWeb has been replaced with “GC intranet”. The web.config has been verified for changes but none were reported. What we are wondering here is whether or not this is the intended behavior, and if so, is there a possible way to hide the GCTools (Gcconnex, etc.) links and keep the text “ESDC/SC IntraWeb” as it would be more relevant for our application. Below, you will find relevant configurations and images

(Under GoC.WebTemplate)
version="v4_0_31"
environment="ESDC_PROD"
useHTTPS="true"

Image 1 : Before the update (using template version 4_0_30, package version 1.30.1)

Image 2 : After the update (using template version 4_0_31, package version 1.31.2)

2-	This may be a feature request rather than a question. The web based application uses custom javascript to submit (POST) the form when pressing select buttons and links that are part of the template. These links (such as links in the left menu) are generated HTML by some Javascript that is part of the CDTS. The problem is that if this javascript were to generate the HTML differently (in the very unlikely event that someone decides to update the file on the CDTS directly without changing the version number), this might break the way the custom javascript references the elements through the selectors.  Also if the server goes offline or the client fails to download the scripts, the custom javascript will also break. The questions is whether it is possible to have an option in the WebTemplateCore  that will give the choice between calling the css and javascript locally rather than relying on the CDTS.

Thank you very much for your help,

Rami El-Hayek
Programmeur, GI-TI
Innovation des Solutions d’affaire (ISA)
Direction générale de l’innovation, de l’information et de la technologie (DGIIT)
Emploi et développement social Canada (EDSC), Gouvernement du Canada
rami.elhayek@servicecanada.gc.ca, Tél.: 819-654-0362

IT/IM Programmer
Business Solutions Innovation (BSI)
Innovation, Information and Technology Branch (IITB)
Employment and Social Development Canada (ESDC), Government of Canada
rami.elhayek@servicecanada.gc.ca / Tel: 819-654-0362

**Comment by MaximMartel** [comment]
@shawnthompson wrote: 

@rami.elhayek This is not something I see us doing in the near future but it might be something the [DotNetTemplates](https://gccode.ssc-spc.gc.ca/iitb-dgiit/sds/GOCWebTemplates/DotNetTemplates) can do.

Thoughts @s.laugh

**Comment by MaximMartel** [comment]
@s-laugh wrote: 

As for (1) the GCTools links, there is an open issue to implement the feature iitb-dgiit/sds/GOCWebTemplates/DotNetTemplates#316

As for (2) the local CSS & JS, the DotNetTemplates already supports a feature called the [Static Fallbacks](https://gccode.ssc-spc.gc.ca/iitb-dgiit/sds/GOCWebTemplates/DotNetTemplates/wikis/Documentation/configurations#setting-the-fallback-files-location) that are actually render first (then overridden by the live CDTS calls), for a situation where CDTS is down, ensuring your site stays up.  
There is also a feature to add your own [custom CSS and JS](https://gccode.ssc-spc.gc.ca/iitb-dgiit/sds/GOCWebTemplates/DotNetTemplates/wikis/Documentation/configurations#adding-your-own-stylesheets-css) where you could attempt to re-add the WET styles and scripts. (CDTS from my understanding doesn't release their scripts, other than grabbing them from source) I wouldn't recommend this approach; it's not what it was designed for and will likely cause you more problems.

**Comment by patricehernert** [comment]
@MaximMartel Could you confirm this issue is still valid for version 4.0.39 ? Thanks.

**Comment by ahmad-shahid** [comment]
This was fixed as part of https://gccode.ssc-spc.gc.ca/iitb-dgiit/sds/GOCWebTemplates/DotNetTemplates/-/issues/316. Closing issue.
