### ISSUE TITLE
RE: BSD-9343 Noticed a difference for the references (English compared to French) - Reference #20190611-150922-000-A

### ISSUE THREAD

**Issue by MaximMartel** [wet-boew/cdts-sgdc#57]
Moved from GCCode:  https://gccode.ssc-spc.gc.ca/iitb-dgiit/nw-ws/sgdc-cdts/issues/144

@StdGit opened issue

Good day Scott and thank you for your patience!

My name is Eric Guitard and I’m with the Content & IA team for Canada.ca at Service Canada. After a brief investigation with our development team, they don’t think the error is related to your pages being slow. Setting an expiration date for a page is more about content delivery optimization and not necessary linked with performance issue.

That said, the link you provided are pages from CDTS which Principal Publisher are not responsible for so I’m forwarding your request to them via this email so they can be aware and  see if they can provide us  with any guidance on this issue.

For further details, please don’t hesitate to contact me.

Thank you again and have a great day!

Eric Guitard

Business Analyst and Information Architect
Citizen Service Branch
Service Canada / Government of Canada
eric.guitard@servicecanada.gc.ca / Tel: 819-654-6162
Analyste des activités et Architecte de l’information
Direction générale de service aux citoyens
Service Canada / Gouvernement du Canada
eric.guitard@servicecanada.gc.ca / Tél. : 819-654-6162

From: aide_web_help@canada.gc.ca aide_web_help@canada.gc.ca
Sent: 11 juin 2019 15:09
To: NC-AIDE_WEB_HELP NC-AIDE_WEB_HELP@canada.gc.ca; Smith, Scott [TC-TC] scott.smith@tc.gc.ca
Subject: BSD-9343 Noticed a difference for the references (English compared to French) - Reference #20190611-150922-000-A

Do not respond to this automatic acknowledgment email.

The Service Desk within the Principal Publisher of Canada.ca will review your request and forward it to the appropriate resolver group for action. As part of our commitment to you and the quality of Canada.ca, we will make every effort to respond to your request in a timely fashion.

Do you have another request? Submit it through the Request form for Canada.ca (http://requestform.portal.gc.ca/tickets.html).

Thank you.

# Summary of your request:

# Reference Number: 20190611-150922-000-A

# Client Name: Scott Smith

# Client Email: scott.smith@tc.gc.ca

# Telephone number: 613-762-0886
Instituteric.guitard@servicecanada.gc.ca / Tel: 819-654-6162ion: Transport Canada

# Issue: Canada_ca_Redesign

# Sub-type: Canada.ca Redesign

# Summary: Noticed a difference for the references (English compared to French)

Description:Hi,
We were working on an issue as we received a complaint about a web page loading slowly.

An online tool pointed to these references as not having an expiration, only the French page reports this. The English page doesn't show these issues.

I was wondering if someone could check the French files so we could eliminate this difference as a possible cause for the page load timing difference.

https://www.canada.ca/etc/designs/canada/cdts/gcweb/rn/cdts/compiled/wet-fr.js (expiration not specified)

https://www.canada.ca/etc/designs/canada/cdts/gcweb/v4_0_30/assets/sig-blk-fr.svg (expiration not specified)

https://www.canada.ca/etc/designs/canada/cdts/gcweb/v4_0_30/js/i18n/fr.min.js (expiration not specified)

Thanks,

Scott Smith
613-762-0886

**Comment by MaximMartel** [comment]
[RE_BSD-9343_Noticed_a_difference_for_the_references__English_compared_to_French__-_Reference__20190611-150922-000-A.zip](https://github.com/wet-boew/cdts-sgdc/files/4153976/RE_BSD-9343_Noticed_a_difference_for_the_references__English_compared_to_French__-_Reference__20190611-150922-000-A.zip)

**Comment by patricehernert** [comment]
@MaximMartel Could you confirm this issue is still valid for version 4.0.39 ? Thanks.

**Comment by StdGit** [comment]
Après avoir vérifié le temps d'attente dans FireFox et Chrome pour la version "run" v4_0_39
Avec les options de Cache et No Cache
Pour les 3 fichiers
Nous n'avons noté aucune différence notable.

La seule différence signifative étant que Chrome chargait les fichiers deux fois plus rapidement en moyenne.
Si nous devons faire de plus amples tests nous aurons besoin du même outil que le client a utilisé.
---
After checking the waiting time in Firefox and Chrome for the "run" version V4_0_39
With Cache and  No cache options
For the 3 files
We did not notice any noticeable difference.

The only significant difference being that Chrome loaded files twice as fast on average.

If we need to do further testing we will need the same tool the client used.
