### ISSUE TITLE
Leverage of the jquery of the CDTS

### ISSUE THREAD

**Issue by MaximMartel** [wet-boew/cdts-sgdc#58]
Move from GCCode: https://gccode.ssc-spc.gc.ca/iitb-dgiit/nw-ws/sgdc-cdts/issues/140

@StdGit created the issue

# Chavet, Laurence (PCH) [laurence.chavet@canada.ca](mailto:laurence.chavet@canada.ca) St-Laurent, Christian \[PCH-PCH\] [christian.st-laurent@canada.ca](mailto:christian.st-laurent@canada.ca); Chen, Xiaosong \[PCH-PCH\] [xiaosong.chen@canada.ca](mailto:xiaosong.chen@canada.ca)

Similar bug found in NC-SGDC-CDTS-GD/Issues/Jquery Issues/eiort search template

Hi

In my teams, we are using the CDTS for all our applications. As the CDTS uses and loads jquery, we want to leverage it and use it in our own code

For example, https://app.pch.gc.ca/application/formulaires-forms/bull_mus/abonner-subscribe.app?lang=en loads a custom script https://app.pch.gc.ca/application/formulaires-forms/javax.faces.resource/chinBull.js.app?ln=js that disable the province input if the country input is different from 1 (=Canada).

1. But this script is never triggered at load, as the document.ready function fails (in yellow below).

```
/**
* toogle on/off province field. 
 */

$( document ).ready( function (){
        
        toggleInputs();

}); 

/* Province field must be enabled if Canada is selected */
function toggleInputs() {
        var country = $('[id*="country"]');
        var province = $('[id*="province"]');
        
        if ( $( country ).val() == 1 ) { //if Canada is selected
            $( province ).prop( "disabled", false );
        } else { //any other country
               $( province ).val("none");
               $( province ).prop( "disabled", true );
        }
}
```

![image_github-issue](https://user-images.githubusercontent.com/3074084/73773942-19438580-4751-11ea-8e6a-4fc62ffb5253.png)

2. The script is working as we can see when we manually change the country
3. Also, this works on load if we call explicitly a jquery in the head (added in yellow). But the purpose is to not reload it again, as the CDTS is loading it already and we may introduce a discrepancy (in versions) between our explicit load of the jquery and the one loaded by CDTS.

```
<script type="text/javascript" src="//devapp.pch.gc.ca/sgc-cms/designs/canada/cdts/gcweb/v4_0_32tmp/cdts/compiled/soyutils.js"></script>
    <script type="text/javascript" src="//devapp.pch.gc.ca/sgc-cms/designs/canada/cdts/gcweb/v4_0_32tmp/cdts/compiled/wet-en.js"></script>
    <script type="text/javascript" src="//devapp.pch.gc.ca/sgc-cms/designs/canada/cdts/gcweb/v4_0_32/js/jquery/2.2.4/jquery.js"></script>
```
Another example if I copy the code below on any page just after the h1 => the first part does not trigger (pink, jQuery is not available), the second part triggers properly when clicking on test (jQuery available). This is the same behaviour if I put the script at the footer.

```
<script>
            if (typeof jQuery === 'undefined') {
                  alert("Jquery not available");
            } else {
                  alert("Jquery available");
            }
            
            $( document ).ready ( function (){
              alert("doc ready just after h1 - auto");
            }); 
            

            function test(){
                  if (typeof jQuery === 'undefined') {
                    alert("Jquery not available");
                  } else {
                        alert("Jquery available");
                  }
                        
                  $( document ).ready ( function (){
                     alert("doc ready just after h1 - manually triggered");
                  }); 
            }
            </script>
            <a href="javascript:test();">test</a>
```

Conclusion: what would be the best way to code our js (including jquery code) to be run after the page loaded

1. Change our code, then how to get the jquery loaded by the CDTS available for our scripts?
2. Recall a jquery.js in the header with the risk to have a discrepancy with the version called in the WET
3. Another idea?

Thanks

Laurence Chavet

Gestionnaire, Développement d'applications externes - Direction générale de la Dirigeante principale de l’information et de la transformation Ministère du Patrimoine canadien / Gouvernement du Canada [laurence.chavet@canada.ca](mailto:laurence.chavet@canada.ca) / Tél. : 819-576-2811

Manager, External Applications Development - Chief Information and Transformation Officer Branch Department of Canadian Heritage / Government of Canada [laurence.chavet@canada.ca](mailto:laurence.chavet@canada.ca) / Tel: 819-576-2811

**Comment by MaximMartel** [comment]
@laurencechavet wrote: 

The proposal from the "eiort search template" to move the defRefFooter call directly below the body works well. Could this be done in the CDTS template so all the departments could beneficiate it, and so we would not have to customize the CDTS on our part, which I would like to avoid. Thanks

**Comment by MaximMartel** [comment]
@laurencechavet wrote:
[leverage_of_the_jquery_of_the_CDTS.zip](https://github.com/wet-boew/cdts-sgdc/files/4155205/leverage_of_the_jquery_of_the_CDTS.zip)


Also I am not sure if you can change it, but the message copied in here did not render properly the scripts and therefore is incomplete and incorrect compared to my initial email. I reattach my email here for clarity in case you can not change the original entry [leverage_of_the_jquery_of_the_CDTS.msg](https://gccode.ssc-spc.gc.ca/iitb-dgiit/nw-ws/sgdc-cdts/uploads/9bcd5d289f2206c54459293cf4479a91/leverage_of_the_jquery_of_the_CDTS.msg)

**Comment by laurencechavet** [comment]
Hi, The work around "eiort search template" to move the defRefFooter call directly below the body works well.  But is there a plan to do this in the CDTS template instead of each department to need to override the CDTS to have jquery working on our own scripts? Thanks

**Comment by patricehernert** [comment]
@MaximMartel Could you confirm this issue is still valid for version 4.0.39 ? Thanks.

**Comment by laurencechavet** [comment]
Yes this is still valid. To create a piece of javascript using jquery, we need to include it in the footer. This would be better if directly done by the CDTS to allow jquery for all, instead of the departments to customize the CDTS and this would guarantee this is completely compatible with the CDTS. Thanks

**Comment by StdGit** [comment]
Your issue is cause by the fact that your script is trying to execute before jquery is loaded

Try to defer it after the page is loaded with defer="defer" attribute

`<script> defer="defer" type="text/javascript"  src="/application/formulaires-forms/javax.faces.resource/chinBull.js.app?ln=js"></script>`

It should work for the majority of browsers. https://caniuse.com/script-defer

You could note also that jquery is loaded by 

![image](https://user-images.githubusercontent.com/5129874/105909838-12fb8880-5ff6-11eb-83f8-3cf4f0be2161.png)

Let us know if it works for you.

**Comment by laurencechavet** [comment]
Hi
The defer attribute works fine. Thanks a lot. You can close the case
Thanks
