### ISSUE TITLE
Formation/Discussion sur l'utilisation de la liste de distribution du CDTS

### ISSUE THREAD

**Issue by TTVXStarWake** [wet-boew/cdts-sgdc#59]
Issue moved from GCCode: https://gccode.ssc-spc.gc.ca/iitb-dgiit/nw-ws/sgdc-cdts/issues/139

@StdGit created the issue

Nous pourrions peut-être utiliser une liste de distribution par courriel.
https://fimsvc.hrdc-drhc.net/IdentityManagement/default.aspx
Celle-ci nous permettrait aussi d'envoyer des notifications pour le calendrier.
La liste sur https://www.gcpedia.gc.ca/wiki/Solution_de_gabarits_%C3%A0_d%C3%A9ploiement_centralis%C3%A9_(SGDC)/Inscription  est ouverte à tous, ce qui pourrait occasionner des erreurs, et je ne connais pas le processus de copie dans https://gccode.ssc-spc.gc.ca/iitb-dgiit/nw-ws/sgdc-cdts/wikis/contacts.csv

**Comment by MaximMartel** [comment]
@shawnthompson commented: 

Next release we will send the regular [release email](https://gccode.ssc-spc.gc.ca/iitb-dgiit/nw-ws/sgdc-cdts/wikis/email.release) to notify people of changes, then advise people that it will be the last email we will be sending out and that iot will be their responsibility to "watch" our project to see when changes are made and releases are done.

![](https://gccode.ssc-spc.gc.ca/iitb-dgiit/nw-ws/sgdc-cdts/uploads/11026ba57222fb0d3d44b3a430d76e4e/image.png)

**Comment by patricehernert** [comment]
@MaximMartel Could you confirm this issue is still valid for version 4.0.39 ? Thanks.

**Comment by StdGit** [comment]
Une fois que le projet sera officiellement sur GitHub ce billet pourra être fermé.

---

Once the project will be officially on GitHub this issue could be closed.

**Comment by ahmad-shahid** [comment]
Project is now officially on Github. Closing this issue.
