### ISSUE TITLE
Traduire le site GCcode en Français

### ISSUE THREAD

**Issue by TTVXStarWake** [wet-boew/cdts-sgdc#60]
Move from GCCode: https://gccode.ssc-spc.gc.ca/iitb-dgiit/nw-ws/sgdc-cdts/issues/138

@StdGit created the issue

Traduire le site GcCode en Français en commençant par les Wiki

**Comment by MaximMartel** [comment]
@shawnthompson commented:

If there are any takers... no objections by me.

**Comment by patricehernert** [comment]
@MaximMartel Could you confirm this issue is still valid for version 4.0.39 ? Thanks.

**Comment by StdGit** [comment]
Une fois que le projet sera officiellement sur GitHub ce billet pourra être fermé.

Once the project will be officially on GitHub this issue could be closed.

**Comment by ahmad-shahid** [comment]
We are now officially on Github. Closing this issue.
