### ISSUE TITLE
wb-ready.wb event not triggering 30% of time in chrome

### ISSUE THREAD

**Issue by TTVXStarWake** [wet-boew/cdts-sgdc#61]
Move from GCCode: https://gccode.ssc-spc.gc.ca/iitb-dgiit/nw-ws/sgdc-cdts/issues/137

@StdGit created the issue

Lee, Jimmy Wing-Chuen JimmyWing-Chuen.Lee@tc.gc.ca
Faire un suivi au client d'ici le 2020-01-27

Hi,

We are using CDTS v4.0.30.  We have noticed that the wb-ready.wb event in the code below is not triggering consistently in the Chrome browser, only about 30% of time fired:

![image](https://user-images.githubusercontent.com/3074084/73780896-557ce300-475d-11ea-92a5-93fb7bb4b536.png)

I see the following errors in the browser console:

![image (1)](https://user-images.githubusercontent.com/3074084/73780919-5f064b00-475d-11ea-8f32-507477b4bd9b.png)

![image (2)](https://user-images.githubusercontent.com/3074084/73780942-688fb300-475d-11ea-9556-bb33c7f02809.png)

I tried using the async attribute in the script tag (line# 374), but it is still not working. (https://developers.google.com/web/updates/2016/08/removing-document-write)

**Comment by MaximMartel** [comment]
@shawnthompson commented: 

@StdGit , Any updated on this?

**Comment by patricehernert** [comment]
@MaximMartel Could you confirm this issue is still valid for version 4.0.39 ? Thanks.

**Comment by StdGit** [comment]
Les Développeurs devraient utiliser un script externe avec l'attribut defer
Testé avec Chrome Version 87.0.4280.66 (Official Build) (64-bit)
En attente d'une confirmation de 'Lee, Jimmy Wing-Chuen' <JimmyWing-Chuen.Lee@tc.gc.ca> :-)

Ex:

---

`<script src="externalScript.js" defer></script>`

```
//script externalScript.js

function deferScript(a, b, c) {
	this.a = a;
	this.b = b;
	this.c = c;
  }
  
$(document).on("wb-ready.wb", function (Event) {	  
	const myConst = new deferScript('defer', 'the', 'script');	  
	console.log(myConst.a);
	console.log(myConst.b);
	console.log(myConst.c);	
})
```

---
Developers should use an external script with a defer attribute
Tested with Chrome Version 87.0.4280.66 (Official Build) (64-bit)
Waiting for a confirmation of 'Lee, Jimmy Wing-Chuen' <JimmyWing-Chuen.Lee@tc.gc.ca> :-)

**Comment by ahmad-shahid** [comment]
Have not heard back. Will close this issue. Re-open if this is still an issue.
