### ISSUE TITLE
Add default in documentation and template

### ISSUE THREAD

**Issue by MaximMartel** [wet-boew/cdts-sgdc#63]
Moved from GCCode: https://gccode.ssc-spc.gc.ca/iitb-dgiit/nw-ws/sgdc-cdts/issues/135

@StdGit created the issue

We should define default value for the variables we use:

**Comment by MaximMartel** [comment]
@shawnthompson commented:

I agree. Move to [Documentation](https://github.com/cenw-wscoe/sgdc-cdts).

**Comment by patricehernert** [comment]
@MaximMartel Could you confirm this issue is still valid for version 4.0.39 ? Thanks.

**Comment by ahmad-shahid** [comment]
The script was removed.
