### ISSUE TITLE
Verify if it is possible to change the warning window in exitScript for a Modal window

### ISSUE THREAD

**Issue by MaximMartel** [wet-boew/cdts-sgdc#64]
Moved from GCCode: https://gccode.ssc-spc.gc.ca/iitb-dgiit/nw-ws/sgdc-cdts/issues/133

@StdGit created this issue

https://ssl-templates.services.gc.ca/app/cls/WET/gcweb/v4_0_32/cdts/samples/exitscript-en.shtml

**Comment by StdGit** [comment]
If you look modal-popup

https://wet-boew.github.io/wet-boew/demos/lightbox/lightbox-en.html

And you click in the dark area, the window doesn’t close
in cdts it's closing. It is an enhacement...

But perhaps user prefer the way it is.

https://ssl-templates.services.gc.ca/app/cls/WET/gcweb/v4_0_32/cdts/appTop/refFooter_exitscript-en.shtml
https://ssl-templates.services.gc.ca/app/cls/WET/gcintranet/v4_0_32/cdts/appTop/refFooter_exitscript-en.shtml

Contenu superposé centré - Modal (Lightbox + Modal)

<a id="sExitModalLink" class="wb-lbx lbx-modal wb-inv wb-init wb-lbx-inited" title="" href="#sExitModal" tabindex="-1">Secure exit notice</a>

<section id="sExitModal" class="modal-dialog modal-content overlay-def">
	<header class="modal-header">
		<h2 class="modal-title" id="lbx-title">Warning</h2>
	</header>
	<div class="modal-body">
		<p>This is a custom message. You are about to leave a secure site, do you wish to continue?</p>
		<ul class="list-inline text-center"><li><a class="btn btn-primary popup-modal-dismiss pull-left" id="eCancel" href="javascript:void(0)" type="button">Nope</a></li><li><a class="btn btn-default popup-modal pull-right" id="eOK" href="javascript:void(0)" type="button">Sure</a></li></ul></div><div class="modal-footer"><button type="button" class="btn btn-sm btn-primary pull-left popup-modal-dismiss" title="Close overlay">Close<span class="wb-inv">Close overlay</span></button>
	</div>
	<button title="Close overlay (escape key)" type="button" class="mfp-close">×<span class="wb-inv"> Close overlay (escape key)</span></button>
</section>

**Comment by patricehernert** [comment]
@MaximMartel Could you confirm this issue is still valid for version 4.0.39 ? Thanks.

**Comment by ahmad-shahid** [comment]
In the latest release (v4.0.39), we are now using the exitScript feature provided by WET. We can modify the content (i.e. the message, button labels) but cannot change the the warning window itself.
