### ISSUE TITLE
GCWeb: AppTop: Skip to footer

### ISSUE THREAD

**Issue by TTVXStarWake** [wet-boew/cdts-sgdc#65]
Issue moved from GCCode: https://gccode.ssc-spc.gc.ca/iitb-dgiit/nw-ws/sgdc-cdts/issues/132

@shawnthompson opened the issue

When in mobile view the skip to link doesn't have a skip to About this application link but the footer is still there

**Comment by patricehernert** [comment]
@MaximMartel Could you confirm this issue is still valid for version 4.0.39 ? Thanks.

**Comment by ahmad-shahid** [comment]
Fixed (v4.0.43). Mobile view now shows link.

![image](https://user-images.githubusercontent.com/52757738/124486261-67601c80-dd7b-11eb-95b3-58c7a0152b7b.png)
