### ISSUE TITLE
Vérifier dans appfooter_transactional-en.shtml

### ISSUE THREAD

**Issue by MaximMartel** [wet-boew/cdts-sgdc#67]
Issue moved from GCCode: https://gccode.ssc-spc.gc.ca/iitb-dgiit/nw-ws/sgdc-cdts/issues/129

@StdGit created the issue

https://ssl-templates.services.gc.ca/app/cls/WET/gcweb/v4_0_32/cdts/appTop/appfooter_transactional-en.shtml

Vérifier si les links sont modifiables, si oui changer l'exemple

![1](https://user-images.githubusercontent.com/3074084/73950634-3cde0b80-48ca-11ea-9bb2-135522580591.png)

**Comment by MaximMartel** [comment]
@shawnthompson commented: 

Juste les liens some modifiables pas le texte. Please close if this answers your question.

**Comment by patricehernert** [comment]
@MaximMartel Could you confirm this issue is still valid for version 4.0.39 ? Thanks.

**Comment by ahmad-shahid** [comment]
Question answered by Shawn. Closing issue.
