### ISSUE TITLE
In IE11 apptop_all-fr.shtml (english is ok) the gray band in the footer should be full screen

### ISSUE THREAD

**Issue by MaximMartel** [wet-boew/cdts-sgdc#68]
Issue moved from GCCode: https://gccode.ssc-spc.gc.ca/iitb-dgiit/nw-ws/sgdc-cdts/issues/128

@StdGit created the issue

https://ssl-templates.services.gc.ca/app/cls/WET/gcweb/v4_0_32/cdts/appTop/apptop_all-fr.shtml
FireFox and Edge are ok

See image
Probably something with `div class="brand"`

![2](https://user-images.githubusercontent.com/3074084/73953460-6ac54f00-48ce-11ea-8951-51a02715a55e.png)

**Comment by patricehernert** [comment]
@MaximMartel Could you confirm this issue is still valid for version 4.0.39 ? Thanks.

**Comment by ahmad-shahid** [comment]
IE11 is not supported anymore. We are currently using WET v4.0.39.1 which does not support IE11. Closing this issue.
