### ISSUE TITLE
French version with CustomSearch 

### ISSUE THREAD

**Issue by DBlaisAsc** [wet-boew/cdts-sgdc#681]
Hi

I'm trying new CTDS .net package (2.7.0).  If I leave default search, I see in french "Rechercher dans Canada.ca".

If I define CustomSearch, it automatically add prefix "Recherche dans ".  Without R.  I see all static files are "Rechercher dans".  I think this was forgetted.

Regards

**Comment by ahmad-shahid** [comment]
Hello, can you tell me the steps you took in order to reach this issue?

Did you start off with a brand new project? or just update to 2.7.0?

Also, is this for MVC, CoreMVC, or Webforms?

**Comment by DBlaisAsc** [comment]
This is a ASP.NET MVC project, that was with 2.6.1, and I updated to 2.7.0.  Please note I never got an "R" there.  I was hoping this was changed in 2.7.0.

I'm doing this to use custom search :

    WebTemplateModel.CustomSearch = new CustomSearch
	{
		Placeholder = IsFrench ? "dans l’Agence spatiale canadienne" : "Canadian Space Agency",
		...
	};

**Comment by ahmad-shahid** [comment]
what is "R"?

so is the issue that you don't want to see the prefix "Rechercher dans" ?

**Comment by DBlaisAsc** [comment]
No, this is the suffix R that is missing.
Default search, placeholder is "Rechercher dans canada.ca".
With custom search, placeholder begin (hardcoded) with "Recherche ".  Recherche without R at end.
I see, all WET static files are with "Rechercher".  That word should be constant.

**Comment by ahmad-shahid** [comment]
Ok thanks, we'll have that fixed
