### ISSUE TITLE
GCIntranet: Breadcrumbs default

### ISSUE THREAD

**Issue by MaximMartel** [wet-boew/cdts-sgdc#69]
Move from GCCode: https://gccode.ssc-spc.gc.ca/iitb-dgiit/nw-ws/sgdc-cdts/issues/127

@shawnthompson created the issue

Should the breadcrumbs have a default home like GCWeb?

https://ssl-templates.services.gc.ca/app/cls/WET/gcintranet/v4_0_32/cdts/appTop/appname-fr.shtml

GCIntranet doesn't

**Comment by patricehernert** [comment]
@MaximMartel Could you confirm this issue is still valid for version 4.0.39 ? Thanks.

**Comment by ahmad-shahid** [comment]
This is speculation at this point as no requirement has been received. This issue can be shelved for now.
