### ISSUE TITLE
Submodules for example pages

### ISSUE THREAD

**Issue by shawnthompson** [wet-boew/cdts-sgdc#7]
Setup git [submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules) for sample pages.

Need to create new repo to put them in.

**Comment by shawnthompson** [comment]
Decided to use npm to pull project down instead of submodules.

First step is getting a package.json file in the docs repo : https://github.com/cenw-wscoe/sgdc-cdts

**Comment by ipaksc** [comment]
The pages have been moved to GitHub
