### ISSUE TITLE
GCIntranet: No Search variant

### ISSUE THREAD

**Issue by TTVXStarWake** [wet-boew/cdts-sgdc#70]
Issue moved from GCCode: https://gccode.ssc-spc.gc.ca/iitb-dgiit/nw-ws/sgdc-cdts/issues/126

@shawnthompson created the issue

When there's no search the language link should align to the right

![4](https://user-images.githubusercontent.com/3074084/73957480-69972080-48d4-11ea-8d84-99a0555e7cf2.png)

https://ssl-templates.services.gc.ca/app/cls/WET/gcintranet/v4_0_32/cdts/appTop/apptop_nosearch-fr.shtml

**Comment by patricehernert** [comment]
@MaximMartel Could you confirm this issue is still valid for version 4.0.39 ? Thanks.

**Comment by ahmad-shahid** [comment]
Fixed (v4.0.43)

![image](https://user-images.githubusercontent.com/52757738/124480271-164d2a00-dd75-11eb-96cf-d06e1dd575db.png)
