### ISSUE TITLE
GCIntranet at small view

### ISSUE THREAD

**Issue by TTVXStarWake** [wet-boew/cdts-sgdc#71]
Issue moved from GCCode: https://gccode.ssc-spc.gc.ca/iitb-dgiit/nw-ws/sgdc-cdts/issues/125

@shawnthompson created the issue.

When you resize the window to small view, the GCTools list of links drop (expected) but the search and language link doesn't line up to the right (they should)

https://ssl-templates.services.gc.ca/app/cls/WET/gcintranet/v4_0_32/cdts/appTop/refFooter_exiturl-en.shtml 

![5](https://user-images.githubusercontent.com/3074084/73959912-0ad3a600-48d8-11ea-8b73-e5839e94cd22.png)

https://ssl-templates.services.gc.ca/app/cls/WET/gcintranet/v4_0_32/cdts/appTop/refFooter_exitscript-fr.shtml

**Comment by patricehernert** [comment]
@MaximMartel Could you confirm this issue is still valid for version 4.0.39 ? Thanks.

**Comment by ahmad-shahid** [comment]
Fixed (v4.0.43)

![image](https://user-images.githubusercontent.com/52757738/124478923-b0ac6e00-dd73-11eb-939e-20edef5c6542.png)
