### ISSUE TITLE
Modifier le texte de la page exiturl-en-fr.shtml pour indiquer que cette page fonctionne avec exitScript

### ISSUE THREAD

**Issue by MaximMartel** [wet-boew/cdts-sgdc#72]
Moved from GCCode: https://gccode.ssc-spc.gc.ca/iitb-dgiit/nw-ws/sgdc-cdts/issues/123

@StdGit created this issue

**Comment by MaximMartel** [comment]
@shawnthompson commented:

@StdGit Please add more detail

**Comment by patricehernert** [comment]
@MaximMartel Could you confirm this issue is still valid for version 4.0.39 ? Thanks.

**Comment by ahmad-shahid** [comment]
@StdGit Can you add more detail? What is the issue? Thanks

**Comment by ahmad-shahid** [comment]
The text on the exit script sample pages describe the functionality. Closing issue.
