### ISSUE TITLE
Investigate possiblity of spell check during tests

### ISSUE THREAD

**Issue by plup2** [wet-boew/cdts-sgdc#743]
Investigate spell checking samples pages (page text, not markup, excluding code blocks) during tests to detect typos and stuff like english text on french page

(also investigate possiblity to add that to JavaTemplates, DotNetTemplates AND documention repo)

**Comment by ahmad-shahid** [comment]
Issue completed (via https://github.com/wet-boew/cdts-sgdc/pull/827)
