### ISSUE TITLE
Verify &nbsp in code

### ISSUE THREAD

**Issue by MaximMartel** [wet-boew/cdts-sgdc#75]
Moved from GCCode: https://gccode.ssc-spc.gc.ca/iitb-dgiit/nw-ws/sgdc-cdts/issues/107

@StdGit created the issue

Some &nbsp (space) could interfere with ie rendering

We must check to remove them

**Comment by ipaksc** [comment]
@StdGit Could you provide an example? I can check it...

**Comment by patricehernert** [comment]
@MaximMartel Could you confirm this issue is still valid for version 4.0.39 ? Thanks.

**Comment by ahmad-shahid** [comment]
Not supported. Closing issue.
