### ISSUE TITLE
subtheme-iservice-en/fr Unmatched end tag

### ISSUE THREAD

**Issue by TTVXStarWake** [wet-boew/cdts-sgdc#76]
Issue moved from GCCode: https://gccode.ssc-spc.gc.ca/iitb-dgiit/nw-ws/sgdc-cdts/issues/106

@StdGit created the issue

http://gcintranet/app/cls/WET/gcintranet/v4_0_32/cdts/samples/subtheme-iservice-en.shtml http://gcintranet/app/cls/WET/gcintranet/v4_0_32/cdts/samples/subtheme-iservice-fr.shtml

**Comment by MaximMartel** [comment]
@shawnthompson commented:

Can we get more information about this issue?

https://ssl-templates.services.gc.ca/app/cls/WET/gcintranet/v4_0_32/cdts/samples/subtheme-iservice-en.shtml https://ssl-templates.services.gc.ca/app/cls/WET/gcintranet/v4_0_32/cdts/samples/subtheme-iservice-fr.shtml

Those pages validate?

**Comment by MaximMartel** [comment]
@shawnthompson commented: 

@StdGit  What do you mean by Unmatched end tag?

**Comment by nschonni** [comment]
Neither page validates
https://validator.w3.org/nu/?doc=http%3A%2F%2Fwww.gcintranet.com%2Fapp%2Fcls%2FWET%2Fgcintranet%2Fv4_0_32%2Fcdts%2Fsamples%2Fsubtheme-iservice-en.shtml
https://validator.w3.org/nu/?doc=http%3A%2F%2Fwww.gcintranet.com%2Fapp%2Fcls%2FWET%2Fgcintranet%2Fv4_0_32%2Fcdts%2Fsamples%2Fsubtheme-iservice-fr.shtml

**Comment by patricehernert** [comment]
@MaximMartel Could you confirm this issue is still valid for version 4.0.39 ? Thanks.

**Comment by ahmad-shahid** [comment]
@StdGit Can you provide more detail, which end tag is unmatched?

**Comment by nschonni** [comment]
https://validator.w3.org/nu/?doc=http%3A%2F%2Fwww.gcintranet.com%2Fapp%2Fcls%2FWET%2Fgcintranet%2Fv4_0_39%2Fcdts%2Fsamples%2Fsubtheme-iservice-en.shtml
Still has errors with 4.0.39

**Comment by StdGit** [comment]
@ahmad-shahid 
https://validator.w3.org/nu/?doc=https%3A%2F%2Fssl-templates.services.gc.ca%2Fapp%2Fcls%2FWET%2Fgcintranet%2Fv4_0_39%2Fcdts%2Fsamples%2Fsubtheme-iservice-en.shtml

    Error: Stray end tag code.

    From line 101, column 4; to line 101, column 10

        }]↩});</code></pre>

Also see https://github.com/validator/validator/issues/841

and validate by text input https://validator.w3.org/nu/#textarea 
(different results)

**Comment by ahmad-shahid** [comment]
Fixed: https://validator.w3.org/nu/?doc=https%3A%2F%2Fssl-templates.services.gc.ca%2Fapp%2Fcls%2FWET%2Fgcintranet%2Fv4_0_43%2Fcdts%2Fsamples%2Fsubtheme-iservice-en.html

![image](https://user-images.githubusercontent.com/52757738/124481338-2b768880-dd76-11eb-868f-83e794eb0b7d.png)
