### ISSUE TITLE
File still loading from GitHub ?

### ISSUE THREAD

**Issue by crochefort** [wet-boew/cdts-sgdc#768]
Today I was looking at my network tab and notice that even on CDTS version 4_0_47 ... 
CWeb/assets/wmms-blk is still loading from GitHub despite the file looks fine here 

https://github.com/wet-boew/cdts-sgdc-dist/commit/06bbd3a3192a6f40be6d8076bb176848c22bc740#diff-663180c645c58190f612cc2b4f3cb3046f0a8d52719153c522ea275b072eb501R22

![image](https://user-images.githubusercontent.com/4562025/221953485-24d281fe-cbbf-476c-8bfc-4e3167ea00e5.png)
![image](https://user-images.githubusercontent.com/4562025/221953676-f4a8250a-7242-4e3a-a984-d9fde209865b.png)

Should this being really loading from CDTS and no longer from GitHub ?

**Comment by ahmad-shahid** [comment]
Hello, yes we fixed this issue and is scheduled to be deployed today. It'll be updated automatically later today. 

https://github.com/wet-boew/cdts-sgdc-dist/commit/c959184f040d8d11c9f2a8bf59f762bcf35d2531#diff-2ee98388f882f248c358ce969c5cd2fab233648ffd86407a26ab25ecc6c50ec4

**Comment by crochefort** [comment]
Thanks for that fast answer! :)

**Comment by duboisp** [comment]
@crochefort it should be updated now, the change that @ahmad-shahid is referring has been deployed on production an hour ago.

**Comment by crochefort** [comment]
Thank you I confirm it's ok now!
