### ISSUE TITLE
remove "appSettings": [{"href": "#"}], from apptop_signin_custommenu-en.shtml

### ISSUE THREAD

**Issue by TTVXStarWake** [wet-boew/cdts-sgdc#78]
Moved from GCCode: https://gccode.ssc-spc.gc.ca/iitb-dgiit/nw-ws/sgdc-cdts/issues/104

@StdGit created the issue

"appSettings": [{"href": "#"}],

https://ssl-templates.services.gc.ca/app/cls/WET/gcintranet/v4_0_31/cdts/appTop/apptop_signin_custommenu-en.shtml

**Comment by MaximMartel** [comment]
@shawnthompson commented:

@StdGit Why would we want to do this? Don't we need the `"appSettings": [{"href": "#"}]` in the example?

**Comment by patricehernert** [comment]
@MaximMartel Could you confirm this issue is still valid for version 4.0.39 ? Thanks.

**Comment by ahmad-shahid** [comment]
@StdGit Can we get more details for this issue?

**Comment by ahmad-shahid** [comment]
All samples were revamped which addresses this issue. Closing.
