### ISSUE TITLE
Separate GCIntranet from GC Web

### ISSUE THREAD

**Issue by TTVXStarWake** [wet-boew/cdts-sgdc#81]
Moved from GCCode: https://gccode.ssc-spc.gc.ca/iitb-dgiit/nw-ws/sgdc-cdts/issues/91

@nicolasraymond created this issue

Also fix the footer who looks horrible.

**Comment by MaximMartel** [comment]
@shawnthompson commented: 

thanks for the details!

https://ssl-templates.services.gc.ca/app/cls/WET/gcintranet/v4_0_30/cdts/appTop/appfooter_footersections_esdc-en.shtml

![7](https://user-images.githubusercontent.com/3074084/74042826-42088c80-4996-11ea-8ec2-91446ec921c9.png)

**Comment by MaximMartel** [comment]
@nicolasraymond commented:

didn't want you to bleed from the eyes

**Comment by patricehernert** [comment]
@MaximMartel Could you confirm this issue is still valid for version 4.0.39 ? Thanks.
