### ISSUE TITLE
200% resize

### ISSUE THREAD

**Issue by MaximMartel** [wet-boew/cdts-sgdc#82]
Moved from GCCode: https://gccode.ssc-spc.gc.ca/iitb-dgiit/nw-ws/sgdc-cdts/issues/86

@nicolasraymond created the issue

At 200%, the intranet theme doesn't look good. Overlapping text in the header and split columns in the footer.

https://ssl-templates.services.gc.ca/app/cls/WET/gcintranet/v4_0_28/cdts/samples/content-en.shtml

**Comment by MaximMartel** [comment]
@shawnthompson commented:

This will need to be fixed by TBS on intranet.canada.ca

**Comment by ipaksc** [comment]
I informed TBS (Lavoie, Éric <Eric.Lavoie@tbs-sct.gc.ca>) about this issue. Eric will send this to the web team for them to test and fix.
