### ISSUE TITLE
Review ContactLink inner workings

### ISSUE THREAD

**Issue by MaximMartel** [wet-boew/cdts-sgdc#83]
Moved from GCCode: https://gccode.ssc-spc.gc.ca/iitb-dgiit/nw-ws/sgdc-cdts/issues/81

@StdGit created the issue

### The Problem

Currently there is some confusion as to how the `ContactLink(s)` works in the different environments (AKAMAI, PROD_SSL, ESDC_PROD) and templates (Standard, Application, Transnational).

### The Solution
We need to decide how `ContactLink(s)` should work as a standard and if there is reason for it to behave differently in one of the environment/templates.

**Thing to consider:**

* Can the text of the link be edited
* Can we add a list/array of links (should the `FooterSections` links be used instead in this situation; it currently only renders in the Application template)
* Can a developer add full & partial URL

### How it currently works

We are not totally sure on all the situations...

**Known discrepancies and issues**

* in Application template, only the link can be changed; other allow array of links and can change text
* in ESDC_PROD + Application it doesn't render at all

/cc @shawnthompson @nicolasraymond @lupp

**Comment by MaximMartel** [comment]
@shawnthompson commented:

My suggestion is custom footer link in the application template and custom contact links. Also adding the option to open in a new window option in contact links.

I got this to work in the app template:

```
"contactLink": [{
	"href": "https://google.com",
	"text": "Link1"
},{
	"href": "#",
	"text": "Link2"
},{
	"href": "#",
	"text": "Long link text link"
}]
```

![9](https://user-images.githubusercontent.com/3074084/74057157-4f7f4000-49b1-11ea-8203-e9a4f4f0f1d0.png)

In the GCWeb template, I would suggest leaving it as is, which means they can only change the link to the contact but not the text and no custom footer menu.

**Comment by MaximMartel** [comment]
@StdGit commented:

@shawnthompson  by GCWeb template, do you mean AKAMAI environment?  
If so, even in the Application template?

**Comment by MaximMartel** [comment]
@shawnthompson commented:

@StdGit , GCWeb is the Canada.ca template which is hosted on the Akamai. The Application template, we call AppTop, which is also hosted on Akamai. We host both version on Akamai as well as our internal ssl-templates.services.gc.ca servers but I think the push is for everyone to use the Akamai server due to it's CDN capabilities.

**Comment by MaximMartel** [comment]
@StdGit commented:

There is too many words in the CDTS/DotNet/Java templates that have dual meanings... we need some kind of reference map to it all... (another issue for later)

If we don't let them change the text, then we should also only let them add one link, not a list, otherwise what will be the text of the extra links.

**Comment by MaximMartel** [comment]
@shawnthompson commented:

I thought on the application template, we let them change the text and the URL, on the GCWeb template we only let them change the link (which I don't know if I agree with).

I need to figure out how to create an array without using a `for` statement in Google Closure...

**Comment by MaximMartel** [comment]
@shawnthompson commented:

@StdGit , does your merge close this issue?

**Comment by patricehernert** [comment]
@MaximMartel Could you confirm this issue is still valid for version 4.0.39 ? Thanks.

**Comment by ahmad-shahid** [comment]
@StdGit Looking at the GCCode issue, your code was merged. Does that close this issue?

**Comment by ahmad-shahid** [comment]
Code was merged: https://gccode.ssc-spc.gc.ca/iitb-dgiit/nw-ws/sgdc-cdts/-/merge_requests/34. 
Closing issue.
