### ISSUE TITLE
Change bypass block colour

### ISSUE THREAD

**Issue by MaximMartel** [wet-boew/cdts-sgdc#85]
Moved from GCCode: https://gccode.ssc-spc.gc.ca/iitb-dgiit/nw-ws/sgdc-cdts/issues/75

@nicolasraymond created this issue

**Comment by MaximMartel** [comment]
@shawnthompson commented:

Email sent to Lavoie, Éric \[TBS-SCT\] [Eric.Lavoie@tbs-sct.gc.ca](mailto:Eric.Lavoie@tbs-sct.gc.ca) to request the change

Eric,

Could you look into changing the colour of the skip to navigation link when they receive focus. They are still using the default Canada.ca colours.

![11](https://user-images.githubusercontent.com/3074084/74058120-5909a780-49b3-11ea-96dd-335604c364e5.png)

The CSS rules that control the background colour is:

.wb-sl { background: #335075; color: #fff; font-weight: 700; }

Thanks,

**Comment by ipaksc** [comment]
@nicolasraymond Hi Nicolas: The issue was fixed in v4.0.29. I will close this ticket
