### ISSUE TITLE
Google Analytic inline script element, security issue

### ISSUE THREAD

**Issue by MaximMartel** [wet-boew/cdts-sgdc#86]
Moved from GCCode: https://gccode.ssc-spc.gc.ca/iitb-dgiit/nw-ws/sgdc-cdts/issues/74

@shawnthompson created the issue

By adding the Google Analytics (#63 (closed)) code we broke security policy and need to find a way to hash out the code we injected.
Email from Stephane Gouin:
From: Gouin, Stephane S [NC] 
Sent: June-05-18 9:15 AM
To: Thompson, Shawn S [NC]
Cc: Petkovic Misic, Biljana B [NC]; Ma, Tony T [NC]
Subject: RE: Mise à jour de la SGDC à la version 4.0.28 / CDTS update to version v4.0.28

Hi Shawn,

As per our discussion this morning with regards to latest CDTS release, v28, we discovered an issue with our content security policy. The CSP defined fails when using v28 of CDTS due to the injection by CDTS scripts of inline JS source code to support Google Tag manager.

The only way for us (CVA) to get around this is to use the “unsafe-inline” script-src directive which basically renders the CSP useless since it’d allow ANY inline JS code to potentially be injected into the page. (high security risk XSS)

There are techniques which could be explored to specifically allow inline JS code, by using nonces or hashes.

https://www.troyhunt.com/locking-down-your-website-scripts-with-csp-hashes-nonces-and-report-uri/

For now, we’ll have to revert back to v27 which doesn’t have inline JS injected and we’ll wait for a CDTS update to address this issue.

**Comment by patricehernert** [comment]
@MaximMartel Could you confirm this issue is still valid for version 4.0.39 ? Thanks.

**Comment by ahmad-shahid** [comment]
The script has been removed. Closing issue.
