### ISSUE TITLE
GCWeb: English Server page: Console Error

### ISSUE THREAD

**Issue by MaximMartel** [wet-boew/cdts-sgdc#87]
Moved from GCCode: https://gccode.ssc-spc.gc.ca/iitb-dgiit/nw-ws/sgdc-cdts/issues/67

@shawnthompson created the issue

This page is giving an error in the console but the French version is not.

TypeError: defPreFooter is null

https://ssl-templates.services.gc.ca//app/cls/WET/gcweb/v4_0_28/cdts/samples/server-en.shtml

**Comment by patricehernert** [comment]
@MaximMartel Could you confirm this issue is still valid for version 4.0.39 ? Thanks.

**Comment by ahmad-shahid** [comment]
Not an issue anymore. See https://ssl-templates.services.gc.ca//app/cls/WET/gcweb/v4_0_39/cdts/samples/server-en.shtml
