### ISSUE TITLE
AppTop: CDTS v4.0.26.3 small magnifying glass (Search icon)

### ISSUE THREAD

**Issue by MaximMartel** [wet-boew/cdts-sgdc#88]
Moved from GCCode: https://gccode.ssc-spc.gc.ca/iitb-dgiit/nw-ws/sgdc-cdts/issues/62

@shawnthompson created this issue

Email
From: Yamamoto, Yuko [mailto:yuko.yamamoto@tc.gc.ca] 
Sent: March-16-18 11:37 AM
To: NC-SGDC-CDTS-GD
Subject: CDTS v4.0.26.3 small magnifying glass (Search icon) 

Hello,

We are using CDTS v4.0.26.3. It seems that there is an issue on the Search option.

When a browser is minimized a small magnifying glass (Search icon) appears. When the browser is not minimized there is no Search option.
Could you tell me if there is a way to hide the small magnifying glass icon?

The same issue also occurs on the sample page “/GoCWebTemplateApplicationSample/StandardPage/” GoC.WebTemplate.C3.MVC.Sample.1.0.10.7.nupkg.

![99](https://user-images.githubusercontent.com/3074084/74060511-244c1f00-49b8-11ea-81e3-3c9e2c647d31.png)
![98](https://user-images.githubusercontent.com/3074084/74060515-257d4c00-49b8-11ea-89f1-937b01d36254.png)

Thank you, Yuko Yamamoto Programmer Analyst, Application Management Services (AMS) Transport Canada / Government of Canada yuko.yamamoto@tc.gc.ca / New Tel: (613) 990-0552 / TTY: 1-888-675-6863 Programmeur-Analyste, Services de gestion des applications (SGA) Transports Canada / Gouvernement du Canada yuko.yamamoto@tc.gc.ca / Nouveau Tél. : (613) 990-0552 / ATS : 1-888-675-6863

**Comment by MaximMartel** [comment]
@shawnthompson commtend:

Created a test page on SSL server and it's not doing the same

https://ssl-templates.services.gc.ca/app/cls/WET/gcweb/v4_0_27/cdts/appTop/apptop_search_test.shtml

Email send on April 18, 2018

Problem with the .Net templates

https://gccode.ssc-spc.gc.ca/GOCWebTemplates/DotNetTemplates/issues/197

`customSearch` variable but defined and when it uses anything but `test` the search shows up in mobile.

```
{if isNonnull($customSearch)}
```

https://gccode.ssc-spc.gc.ca/edsc-esdc-centre-expertise/sgdc-cdts/blob/master/app/cls/WET/gcweb/v4_0_28/cdts/uncompiled/appPage-en.soy#L43

Need to change it to an actual working variable.

```
customSearch: [{
  submitScript: "path/formSubmit.asp", // Path to the script to be run when search is submitted action="customSearch.submitScript"
  placeholder: "Search Application Name" //Text to go into placeholder attribute and to add to invisible Search text
}]
```

**Comment by ipaksc** [comment]
This ticket was opened and closed 1 year ago.
https://gccode.ssc-spc.gc.ca/iitb-dgiit/sds/GOCWebTemplates/DotNetTemplates/issues/197
