### ISSUE TITLE
Exit Script URL

### ISSUE THREAD

**Issue by Grant-Russell** [wet-boew/cdts-sgdc#889]
There seems to be an issue with the URL produced when using the Exit script. It seems to be adding /logout? to external links that previous versions didn't (I tried 4_0_29)
4.0.47:
![image](https://github.com/wet-boew/cdts-sgdc/assets/138128096/82601ba1-90bb-497f-96a5-d6525643506b)
http://localhost:8080/sinom/logout?targetUrl=https%3A%2F%2Fwww.canada.ca%2Fen%2Femployment-social-development%2Fservices%2Fsin%2Fapply.html (from inspection)
4.0.29
![image](https://github.com/wet-boew/cdts-sgdc/assets/138128096/0f4fef72-6363-41ce-914d-3227cfa7eaa6)
https://www.canada.ca/en/employment-social-development/services/sin/apply.html (from inspection)

When an exitUrl property is specified, any external URL opened in a new tab appears to log the user out.

**Comment by ahmad-shahid** [comment]
Hello, the URL that is specified for the exitURL parameter is added to external links. This is so that users can be redirected to a another page before continuing on to the desired page. 

For example, in URL that you provided, it looks like you specified "logout" for exitURL parameter. 

This is an optional feature. If you don't want that, then remove the exitURL parameter from your code.

**Comment by Grant-Russell** [comment]
> Hello, the URL that is specified for the exitURL parameter is added to external links. This is so that users can be redirected to a another page before continuing on to the desired page.
> 
> For example, in URL that you provided, it looks like you specified "logout" for exitURL parameter.
> 
> This is an optional feature. If you don't want that, then remove the exitURL parameter from your code.

We still do need the exitURL parameter. We also need to be able to open external links in new tabs without "logging the user out". Once one link is opened, any other links they open on that page will open the page they would receive if they had logged out.

**Comment by Grant-Russell** [comment]
> > We also need to be able to open external links in new tabs without "logging the user out".
> 
> Use the exitDomains parameter to have hostnames part of the exception list. Exit script will not be applied for hostnames part of this list. See our sample page for more info: https://cdts.service.canada.ca/app/cls/WET/gcweb/v4_0_47/cdts/samples/exitscript-en.html

We do need the exit script to be hit so the logout happens but the links/domain we want excluded are canada.ca. It's an odd scenario but I don't know that the exitDomains parameter will work here.

**Comment by ahmad-shahid** [comment]
Basically, you would like specific links of your choosing to be exempted from the exit script completely, correct?

If that is the case, I'm thinking of having an attribute that you can add to your link (for example: cdts-exiturl-disabled = "true") and so CDTS would recognize that attribute and exempt that link from the exit script. 

Will that work for you?

**Comment by Grant-Russell** [comment]
> Basically, you would like specific links of your choosing to be exempted from the exit script completely, correct?
> 
> If that is the case, I'm thinking of having an attribute that you can add to your link (for example: cdts-exiturl-disabled = "true") and so CDTS would recognize that attribute and exempt that link from the exit script.
> 
> Will that work for you?

That's exactly it, there are certain links within the canada.ca domain that we need to miss the exit script when the link is opened in a new tab. With an attribute that exempts the link, would the script still be hit if opened in the same tab?

**Comment by Grant-Russell** [comment]
> With that attribute, the exitscript would not hit regardless of if you open in the same tab or new window.
> 
> Because opening in new tab depends on if you have attribute target="_blank" set to your link. Exitscript doesn't check for that.
> 
> That works for you?

Sorry for the late reply but I think this will work yes

**Comment by ahmad-shahid** [comment]
It depends on when our release is scheduled for. Right now, we just did a release and the deployment has not been completed yet (scheduled for next week). 

This means that the fix for this issue will go in our next release which we haven't even begun preparations for. It is very hard to say right now but it will take a couple months at the minimum (might be more).
