### ISSUE TITLE
GCIntranet: ESDC: Activities and initiatives

### ISSUE THREAD

**Issue by MaximMartel** [wet-boew/cdts-sgdc#89]
Moved from GCCode: https://gccode.ssc-spc.gc.ca/iitb-dgiit/nw-ws/sgdc-cdts/issues/61

@shawnthompson created the issue

Create a file that the Intranet team can update the Activities and initiatives themselves.
Contacts:

* Tang, Qinying Q [NC] qinying.tang@hrsdc-rhdcc.gc.ca
* NC-CS-SC-PFOLIO-WEB-WEB-MINIST-INTRANET-GD NC-CS-SC-PFOLIO-WEB-WEB-MINIST-INTRANET-GD@hrdc-drhc.net

Contact at TBS: Lavoie, Éric [Eric.Lavoie@tbs-sct.gc.ca](mailto:Eric.Lavoie@tbs-sct.gc.ca)

**Comment by shawnthompson** [comment]
I will be closing this. The initiatives have been removed.
