### ISSUE TITLE
GCWeb: Exit script

### ISSUE THREAD

**Issue by MaximMartel** [wet-boew/cdts-sgdc#90]
Moved from GCCode: https://gccode.ssc-spc.gc.ca/iitb-dgiit/nw-ws/sgdc-cdts/issues/59

@shawnthompson created the issue

They claim that this is preventing them of tracking the yes button.

https://gccode.ssc-spc.gc.ca/edsc-esdc-centre-expertise/sgdc-cdts/blob/master/app/cls/WET/gcweb/v4_0_28/cdts/exitScript-opt-nomin.txt#L91

```javascript
// Prevent navigation
event.preventDefault();
// Testing
//alert(exitURL + '?exitdomain='+ getHost(exitURL) +'&targetUrl=' + targetUrl + '&targetdomain='+ getHost(targetUrl) +'&pageLang=' + pageLang);
// Before redirecting confirm user wants to leave site
$("#sExitModalLink").trigger("open.wb-lbx", [
    [
        {
            src: "#sExitModal",
            type: "inline"
        }
    ],
    true
]);
```

# Email

From: Haase, Dainton
Sent: February-13-18 2:48 PM 
To: Raymond, Nicolas N \[NC\]; Thompson, Shawn S \[NC\] 
Subject: Outbound Link Tracking for MSCA 

Currently, outbound link tracking for analytics, does not function properly on MSCA due to unfavourable interactions with the CDTS exit script. Restoring this functionality has been identified as a priority. 

Background context : 

On MSCA, when an outbound link is clicked, a modal appears 

We would like the tracking to be on the Yes button click event. Right now the exit script does not allow our platform (DTM) to trigger the click event, because the link default action is suppressed. 

It has been determined by our team that before we can move forward with this item, our team would like to consult with the MSCA developers to determine if a change in coding is feasible. 

Thanks very much, I look forward to hearing back from you 

Dainton Haase 
Project Manager, Canada.ca Analytics/ Gestionnaire de projet, analytique Web pour Canada.ca Quantum Management Services Limited, Contractor for Service Canada / Les Services de gestion Quantum Limitée, contractant pour Service Canada 
dainton.haase@servicecanada.gc.ca 
819-654-1618

**Comment by patricehernert** [comment]
@MaximMartel Could you confirm this issue is still valid for version 4.0.39 ? Thanks.

**Comment by ahmad-shahid** [comment]
Not applicable anymore. The WET script is now being used. Closing issue.
