### ISSUE TITLE
CDTS Templates missing CSS in rn version

### ISSUE THREAD

**Issue by akheel-syed** [wet-boew/cdts-sgdc#910]
Not sure if this is by design but I am trying to implement the new method of loading CDTS templates and pointing to a specific version of the CSS works, however trying to load the latest through the 'rn' version fails.

Example:
JS
RN version: https://www.canada.ca/etc/designs/canada/cdts/gcweb/rn/cdts/compiled/wet-en.js - works
Specific version: https://www.canada.ca/etc/designs/canada/cdts/gcweb/v4_0_47/cdts/compiled/wet-en.js -works

CSS
RN version: https://www.canada.ca/etc/designs/canada/cdts/gcweb/rn/cdts/cdts-app-styles.css - **fails**
Specific version: https://www.canada.ca/etc/designs/canada/cdts/gcweb/v4_0_47/cdts/cdts-app-styles.css - works

**Comment by ahmad-shahid** [comment]
Hello, the new method is currently not available for 'rn' version because that file is currently missing (we haven't done the run release yet). 

We have plans on doing our 'rn' release in a few weeks. Thank you.
