### ISSUE TITLE
Exhaustive list of JSON objects?

### ISSUE THREAD

**Issue by MaximMartel** [wet-boew/cdts-sgdc#93]
Moved from GCCode: https://gccode.ssc-spc.gc.ca/sgdc-cdts/sgdc-cdts/issues/15

Greg Baker created the issue

I'm wondering if there is a list of all JSON objects used by CDTS and their properties anywhere that I can reference. For example, when I call ```wet.builder.appTop({ .. })```, I'd like to know all of the possible properties that can be passed in (ex: ```appName```, ```breadcrumbs```, ```signOut```, etc). Going through the minified script files to discover these is a real pain.

My goal is to create representations of these JS objects in Java so I can use Jackson to serialize them into JSON.

**Comment by MaximMartel** [comment]
@shawnthompson commented:

They can be found in the *great* GCPedia documentation we put together, which needs to be simplified.

http://www.gcpedia.gc.ca/wiki/Centrally_Deployed_Templates_Solution_(CDTS)

I like the idea of creating a JSON of all the options, if you have the time to put something together and share it with us, that would be very much appreciated.

**Comment by MaximMartel** [comment]
Greg Baker commented:

Thanks @Shawn.Thompson. I have looked at that page and did see some of the available options, but I wasn't sure if the list was exhaustive. Also, it doesn't specify what *values* are allowed for the options.

Example from linked documentation (notice no listed values):

> * Did you add wet.builder.appTop?
>   * Available options are cdnEnv, appName, lngLinks, secure, signIn, signOut, search, customSearch, siteMenu, menuPath, showPreContent and breadcrumbs

I took a look at the [JavaTemplates](https://gccode.ssc-spc.gc.ca/iitb-dgiit/sds/GOCWebTemplates/JavaTemplates.git) project and they do have a lot of what I'm looking for already coded, but it would be nice to have an official list available in an easy to read document.

Is there any information about what values are allowed for each of the options? Maybe I just can't find the document.

**Comment by MaximMartel** [comment]
@shawnthompson commented:

We need to update the documentation but too many priorities at the moment keeps pushing it back, plus GCPedia sucks.

We are moving the documentation to [a repo on github.com](https://github.com/cenw-wscoe/sgdc-cdts/tree/gh-pages/docs) to make it available to those who can't access GCPedia (contractors).

Not ready for prime: https://cenw-wscoe.github.io/sgdc-cdts/docs/index-en.html

Again, time or resources is needed to make the move / update.

**Comment by MaximMartel** [comment]
Greg Baker commented:

Cool.. I like it.

One final question: is there a non-minified version of CDTS anywhere that can be referenced (I don't see it on github)? I can extract what I need from the source. I could probably do it using the minified version but that would be less-than-fun.

**Comment by MaximMartel** [comment]
@shawnthompson commented:

@gregory.j.baker no it's still a closed source project for now.

**Comment by patricehernert** [comment]
@MaximMartel Could you confirm this issue is still valid for version 4.0.39 ? Thanks.

**Comment by ahmad-shahid** [comment]
Question has been answered. Also, note: documentation can be found here: https://cenw-wscoe.github.io/sgdc-cdts/docs/internet-en.html
