### ISSUE TITLE
Intranet fonts not loading - Multiple CORS header

### ISSUE THREAD

**Issue by sonya-chenard** [wet-boew/cdts-sgdc#945]
We have started getting errors when loading the fonts from https://templates.service.gc.ca, this does not happen when loading from www.canada.ca. 

### error in console showing:
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://templates.service.gc.ca/app/cls/WET/gcintranet/v4_0_45/wet-boew/fonts/glyphicons-halflings-regular.woff2. (Reason: Multiple CORS header ‘Access-Control-Allow-Origin’ not allowed).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://templates.service.gc.ca/app/cls/WET/gcintranet/v4_0_45/wet-boew/fonts/glyphicons-halflings-regular.woff. (Reason: Multiple CORS header ‘Access-Control-Allow-Origin’ not allowed).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://templates.service.gc.ca/app/cls/WET/gcintranet/v4_0_45/wet-boew/fonts/glyphicons-halflings-regular.ttf. (Reason: Multiple CORS header ‘Access-Control-Allow-Origin’ not allowed).

This results in funny looking characters showing up instead of the font
![Screenshot 2023-09-08 093555](https://github.com/wet-boew/cdts-sgdc/assets/94059187/8e151b59-e190-4be9-a7a5-3e4549208b6d)

**Comment by ahmad-shahid** [comment]
Hello, can you try again? it should be resolved now.

**Comment by sonya-chenard** [comment]
Salut,

Seems to be working from localhost and Sade servers but not in production (ex: from srv213.prv).

Thank you,
Sonya

**Comment by sonya-chenard** [comment]
any idea when this will be fixed for **Prod**?

**Comment by ahmad-shahid** [comment]
The problem was happening because of a fix that was applied but it was reverted this morning. The issue should not be present anymore. Can you try hard refreshing your page on prod?

**Comment by sonya-chenard** [comment]
Sorry, my bad. I Cleared the cache, the revert fixed the problem.

Thank you!

**Comment by ahmad-shahid** [comment]
Happy to hear! thank you
