### ISSUE TITLE
Property name not standardized `CustomFooterLinks`

### ISSUE THREAD

**Issue by MaximMartel** [wet-boew/cdts-sgdc#96]
Moved from GCCode: https://gccode.ssc-spc.gc.ca/sgdc-cdts/sgdc-cdts/issues/12

@StdGit created the issue

The property CustomFooterLinks isn’t in cammelCase.

If it could be fixed, that would be great. If not, this lets others know why they might be having trouble.

**Comment by MaximMartel** [comment]
@shawnthompson commented:

Thanks for letting us know, we will correct this to `customFooterLinks`

**Comment by ipaksc** [comment]
The issue was fixed in v4.0.30
