### ISSUE TITLE
Allow for the "Account Settings" label in the application template to be overriden via a parameter

### ISSUE THREAD

**Issue by TTVXStarWake** [wet-boew/cdts-sgdc#97]
Moved from GCCode: https://gccode.ssc-spc.gc.ca/sgdc-cdts/sgdc-cdts/issues/11

Stephane Gouin created the issue

Clients have requested to have this label changed to something else, so we'd like a supported way of configuring this label via the CDTS configuration parameters in the appTopParams

**Comment by MaximMartel** [comment]
@shawnthompson commented:

@StdGit Let's work on this for next release

**Comment by patricehernert** [comment]
@MaximMartel Could you confirm this issue is still valid for version 4.0.39 ? Thanks.

**Comment by ahmad-shahid** [comment]
Requested Stephane Gouin to confirm if this issue was still valid but did not receive a response. Closing issue.
