### ISSUE TITLE
Move under the WET org?

### ISSUE THREAD

**Issue by MaximMartel** [wet-boew/cdts-sgdc#99]
Moved from GCCode: https://gccode.ssc-spc.gc.ca/sgdc-cdts/sgdc-cdts/issues/7

@nschonni created the issue
 
I believe this has been raised before, but is there a reason this is being done on GC Code rather than GitHub.
It's been mentioned on some of the other issues that people still post the Issues to WET or the GCWeb theme since they assume the issue lays there.

I can understand that maybe there is some secret sauce stuff like global program changes in the headers/footers that you don't want to publish till it's public, but that could be kept here and pushed to the public repo once it's live on the site.

**Comment by MaximMartel** [comment]
@nschonni commented: 

Related https://gccode.ssc.gc.ca/ssc-innovation-group/ssc-gitlab-pilot/issues/57

**Comment by MaximMartel** [comment]
@shawnthompson commented:

Fixed your link: https://gccode.ssc-spc.gc.ca/ssc-innovation-group/ssc-gitlab-pilot/issues/57

**Comment by nschonni** [comment]
Think this one can be closed now that you've migrated
